[build]
  publish = "./dist/"
  command = "export ELM_HOME=\"$NETLIFY_CACHE_DIR/elm\" && npm run build"

[dev]
  command = "npm run start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
