[build]
  publish = "dist"
  command = "npx --no-install elm-tooling install && npm run build || npx --no-install elm-tooling install && npm run build"

[dev]
  command = "npm run start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
