[build]
  publish = "dist"
  command = "export ELM_HOME=\"elm-stuff\" && npm run build"
  
[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["elm-stuff"]

[dev]
  command = "npm run start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
