-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object exposing (..)


type AbortQueuedMigrationsPayload
    = AbortQueuedMigrationsPayload


type AcceptEnterpriseAdministratorInvitationPayload
    = AcceptEnterpriseAdministratorInvitationPayload


type AcceptTopicSuggestionPayload
    = AcceptTopicSuggestionPayload


type ActorLocation
    = ActorLocation


type AddAssigneesToAssignablePayload
    = AddAssigneesToAssignablePayload


type AddCommentPayload
    = AddCommentPayload


type AddDiscussionCommentPayload
    = AddDiscussionCommentPayload


type AddDiscussionPollVotePayload
    = AddDiscussionPollVotePayload


type AddEnterpriseSupportEntitlementPayload
    = AddEnterpriseSupportEntitlementPayload


type AddLabelsToLabelablePayload
    = AddLabelsToLabelablePayload


type AddProjectCardPayload
    = AddProjectCardPayload


type AddProjectColumnPayload
    = AddProjectColumnPayload


type AddProjectDraftIssuePayload
    = AddProjectDraftIssuePayload


type AddProjectNextItemPayload
    = AddProjectNextItemPayload


type AddProjectV2DraftIssuePayload
    = AddProjectV2DraftIssuePayload


type AddProjectV2ItemByIdPayload
    = AddProjectV2ItemByIdPayload


type AddPullRequestReviewCommentPayload
    = AddPullRequestReviewCommentPayload


type AddPullRequestReviewPayload
    = AddPullRequestReviewPayload


type AddPullRequestReviewThreadPayload
    = AddPullRequestReviewThreadPayload


type AddReactionPayload
    = AddReactionPayload


type AddStarPayload
    = AddStarPayload


type AddUpvotePayload
    = AddUpvotePayload


type AddVerifiableDomainPayload
    = AddVerifiableDomainPayload


type AddedToProjectEvent
    = AddedToProjectEvent


type App
    = App


type ApproveDeploymentsPayload
    = ApproveDeploymentsPayload


type ApproveVerifiableDomainPayload
    = ApproveVerifiableDomainPayload


type ArchiveRepositoryPayload
    = ArchiveRepositoryPayload


type AssignedEvent
    = AssignedEvent


type AutoMergeDisabledEvent
    = AutoMergeDisabledEvent


type AutoMergeEnabledEvent
    = AutoMergeEnabledEvent


type AutoMergeRequest
    = AutoMergeRequest


type AutoRebaseEnabledEvent
    = AutoRebaseEnabledEvent


type AutoSquashEnabledEvent
    = AutoSquashEnabledEvent


type AutomaticBaseChangeFailedEvent
    = AutomaticBaseChangeFailedEvent


type AutomaticBaseChangeSucceededEvent
    = AutomaticBaseChangeSucceededEvent


type BaseRefChangedEvent
    = BaseRefChangedEvent


type BaseRefDeletedEvent
    = BaseRefDeletedEvent


type BaseRefForcePushedEvent
    = BaseRefForcePushedEvent


type Blame
    = Blame


type BlameRange
    = BlameRange


type Blob
    = Blob


type Bot
    = Bot


type BranchProtectionRule
    = BranchProtectionRule


type BranchProtectionRuleConflict
    = BranchProtectionRuleConflict


type BranchProtectionRuleConflictConnection
    = BranchProtectionRuleConflictConnection


type BranchProtectionRuleConflictEdge
    = BranchProtectionRuleConflictEdge


type BranchProtectionRuleConnection
    = BranchProtectionRuleConnection


type BranchProtectionRuleEdge
    = BranchProtectionRuleEdge


type BypassForcePushAllowance
    = BypassForcePushAllowance


type BypassForcePushAllowanceConnection
    = BypassForcePushAllowanceConnection


type BypassForcePushAllowanceEdge
    = BypassForcePushAllowanceEdge


type BypassPullRequestAllowance
    = BypassPullRequestAllowance


type BypassPullRequestAllowanceConnection
    = BypassPullRequestAllowanceConnection


type BypassPullRequestAllowanceEdge
    = BypassPullRequestAllowanceEdge


type CWEConnection
    = CWEConnection


type CWEEdge
    = CWEEdge


type CancelEnterpriseAdminInvitationPayload
    = CancelEnterpriseAdminInvitationPayload


type CancelSponsorshipPayload
    = CancelSponsorshipPayload


type ChangeUserStatusPayload
    = ChangeUserStatusPayload


type CheckAnnotation
    = CheckAnnotation


type CheckAnnotationConnection
    = CheckAnnotationConnection


type CheckAnnotationEdge
    = CheckAnnotationEdge


type CheckAnnotationPosition
    = CheckAnnotationPosition


type CheckAnnotationSpan
    = CheckAnnotationSpan


type CheckRun
    = CheckRun


type CheckRunConnection
    = CheckRunConnection


type CheckRunEdge
    = CheckRunEdge


type CheckRunStateCount
    = CheckRunStateCount


type CheckStep
    = CheckStep


type CheckStepConnection
    = CheckStepConnection


type CheckStepEdge
    = CheckStepEdge


type CheckSuite
    = CheckSuite


type CheckSuiteConnection
    = CheckSuiteConnection


type CheckSuiteEdge
    = CheckSuiteEdge


type ClearLabelsFromLabelablePayload
    = ClearLabelsFromLabelablePayload


type ClearProjectV2ItemFieldValuePayload
    = ClearProjectV2ItemFieldValuePayload


type CloneProjectPayload
    = CloneProjectPayload


type CloneTemplateRepositoryPayload
    = CloneTemplateRepositoryPayload


type CloseIssuePayload
    = CloseIssuePayload


type ClosePullRequestPayload
    = ClosePullRequestPayload


type ClosedEvent
    = ClosedEvent


type CodeOfConduct
    = CodeOfConduct


type CommentDeletedEvent
    = CommentDeletedEvent


type Commit
    = Commit


type CommitComment
    = CommitComment


type CommitCommentConnection
    = CommitCommentConnection


type CommitCommentEdge
    = CommitCommentEdge


type CommitCommentThread
    = CommitCommentThread


type CommitConnection
    = CommitConnection


type CommitContributionsByRepository
    = CommitContributionsByRepository


type CommitEdge
    = CommitEdge


type CommitHistoryConnection
    = CommitHistoryConnection


type Comparison
    = Comparison


type ComparisonCommitConnection
    = ComparisonCommitConnection


type ConnectedEvent
    = ConnectedEvent


type ContributionCalendar
    = ContributionCalendar


type ContributionCalendarDay
    = ContributionCalendarDay


type ContributionCalendarMonth
    = ContributionCalendarMonth


type ContributionCalendarWeek
    = ContributionCalendarWeek


type ContributionsCollection
    = ContributionsCollection


type ConvertProjectCardNoteToIssuePayload
    = ConvertProjectCardNoteToIssuePayload


type ConvertPullRequestToDraftPayload
    = ConvertPullRequestToDraftPayload


type ConvertToDraftEvent
    = ConvertToDraftEvent


type ConvertedNoteToIssueEvent
    = ConvertedNoteToIssueEvent


type ConvertedToDiscussionEvent
    = ConvertedToDiscussionEvent


type CreateBranchProtectionRulePayload
    = CreateBranchProtectionRulePayload


type CreateCheckRunPayload
    = CreateCheckRunPayload


type CreateCheckSuitePayload
    = CreateCheckSuitePayload


type CreateCommitOnBranchPayload
    = CreateCommitOnBranchPayload


type CreateDiscussionPayload
    = CreateDiscussionPayload


type CreateEnterpriseOrganizationPayload
    = CreateEnterpriseOrganizationPayload


type CreateEnvironmentPayload
    = CreateEnvironmentPayload


type CreateIpAllowListEntryPayload
    = CreateIpAllowListEntryPayload


type CreateIssuePayload
    = CreateIssuePayload


type CreateLinkedBranchPayload
    = CreateLinkedBranchPayload


type CreateMigrationSourcePayload
    = CreateMigrationSourcePayload


type CreateProjectPayload
    = CreateProjectPayload


type CreateProjectV2Payload
    = CreateProjectV2Payload


type CreatePullRequestPayload
    = CreatePullRequestPayload


type CreateRefPayload
    = CreateRefPayload


type CreateRepositoryPayload
    = CreateRepositoryPayload


type CreateSponsorsTierPayload
    = CreateSponsorsTierPayload


type CreateSponsorshipPayload
    = CreateSponsorshipPayload


type CreateTeamDiscussionCommentPayload
    = CreateTeamDiscussionCommentPayload


type CreateTeamDiscussionPayload
    = CreateTeamDiscussionPayload


type CreatedCommitContribution
    = CreatedCommitContribution


type CreatedCommitContributionConnection
    = CreatedCommitContributionConnection


type CreatedCommitContributionEdge
    = CreatedCommitContributionEdge


type CreatedIssueContribution
    = CreatedIssueContribution


type CreatedIssueContributionConnection
    = CreatedIssueContributionConnection


type CreatedIssueContributionEdge
    = CreatedIssueContributionEdge


type CreatedPullRequestContribution
    = CreatedPullRequestContribution


type CreatedPullRequestContributionConnection
    = CreatedPullRequestContributionConnection


type CreatedPullRequestContributionEdge
    = CreatedPullRequestContributionEdge


type CreatedPullRequestReviewContribution
    = CreatedPullRequestReviewContribution


type CreatedPullRequestReviewContributionConnection
    = CreatedPullRequestReviewContributionConnection


type CreatedPullRequestReviewContributionEdge
    = CreatedPullRequestReviewContributionEdge


type CreatedRepositoryContribution
    = CreatedRepositoryContribution


type CreatedRepositoryContributionConnection
    = CreatedRepositoryContributionConnection


type CreatedRepositoryContributionEdge
    = CreatedRepositoryContributionEdge


type CrossReferencedEvent
    = CrossReferencedEvent


type Cvss
    = Cvss


type Cwe
    = Cwe


type DeclineTopicSuggestionPayload
    = DeclineTopicSuggestionPayload


type DeleteBranchProtectionRulePayload
    = DeleteBranchProtectionRulePayload


type DeleteDeploymentPayload
    = DeleteDeploymentPayload


type DeleteDiscussionCommentPayload
    = DeleteDiscussionCommentPayload


type DeleteDiscussionPayload
    = DeleteDiscussionPayload


type DeleteEnvironmentPayload
    = DeleteEnvironmentPayload


type DeleteIpAllowListEntryPayload
    = DeleteIpAllowListEntryPayload


type DeleteIssueCommentPayload
    = DeleteIssueCommentPayload


type DeleteIssuePayload
    = DeleteIssuePayload


type DeleteLinkedBranchPayload
    = DeleteLinkedBranchPayload


type DeleteProjectCardPayload
    = DeleteProjectCardPayload


type DeleteProjectColumnPayload
    = DeleteProjectColumnPayload


type DeleteProjectNextItemPayload
    = DeleteProjectNextItemPayload


type DeleteProjectPayload
    = DeleteProjectPayload


type DeleteProjectV2ItemPayload
    = DeleteProjectV2ItemPayload


type DeletePullRequestReviewCommentPayload
    = DeletePullRequestReviewCommentPayload


type DeletePullRequestReviewPayload
    = DeletePullRequestReviewPayload


type DeleteRefPayload
    = DeleteRefPayload


type DeleteTeamDiscussionCommentPayload
    = DeleteTeamDiscussionCommentPayload


type DeleteTeamDiscussionPayload
    = DeleteTeamDiscussionPayload


type DeleteVerifiableDomainPayload
    = DeleteVerifiableDomainPayload


type DemilestonedEvent
    = DemilestonedEvent


type DependabotUpdate
    = DependabotUpdate


type DependabotUpdateError
    = DependabotUpdateError


type DeployKey
    = DeployKey


type DeployKeyConnection
    = DeployKeyConnection


type DeployKeyEdge
    = DeployKeyEdge


type DeployedEvent
    = DeployedEvent


type Deployment
    = Deployment


type DeploymentConnection
    = DeploymentConnection


type DeploymentEdge
    = DeploymentEdge


type DeploymentEnvironmentChangedEvent
    = DeploymentEnvironmentChangedEvent


type DeploymentProtectionRule
    = DeploymentProtectionRule


type DeploymentProtectionRuleConnection
    = DeploymentProtectionRuleConnection


type DeploymentProtectionRuleEdge
    = DeploymentProtectionRuleEdge


type DeploymentRequest
    = DeploymentRequest


type DeploymentRequestConnection
    = DeploymentRequestConnection


type DeploymentRequestEdge
    = DeploymentRequestEdge


type DeploymentReview
    = DeploymentReview


type DeploymentReviewConnection
    = DeploymentReviewConnection


type DeploymentReviewEdge
    = DeploymentReviewEdge


type DeploymentReviewerConnection
    = DeploymentReviewerConnection


type DeploymentReviewerEdge
    = DeploymentReviewerEdge


type DeploymentStatus
    = DeploymentStatus


type DeploymentStatusConnection
    = DeploymentStatusConnection


type DeploymentStatusEdge
    = DeploymentStatusEdge


type DisablePullRequestAutoMergePayload
    = DisablePullRequestAutoMergePayload


type DisconnectedEvent
    = DisconnectedEvent


type Discussion
    = Discussion


type DiscussionCategory
    = DiscussionCategory


type DiscussionCategoryConnection
    = DiscussionCategoryConnection


type DiscussionCategoryEdge
    = DiscussionCategoryEdge


type DiscussionComment
    = DiscussionComment


type DiscussionCommentConnection
    = DiscussionCommentConnection


type DiscussionCommentEdge
    = DiscussionCommentEdge


type DiscussionConnection
    = DiscussionConnection


type DiscussionEdge
    = DiscussionEdge


type DiscussionPoll
    = DiscussionPoll


type DiscussionPollOption
    = DiscussionPollOption


type DiscussionPollOptionConnection
    = DiscussionPollOptionConnection


type DiscussionPollOptionEdge
    = DiscussionPollOptionEdge


type DismissPullRequestReviewPayload
    = DismissPullRequestReviewPayload


type DismissRepositoryVulnerabilityAlertPayload
    = DismissRepositoryVulnerabilityAlertPayload


type DraftIssue
    = DraftIssue


type EnablePullRequestAutoMergePayload
    = EnablePullRequestAutoMergePayload


type Enterprise
    = Enterprise


type EnterpriseAdministratorConnection
    = EnterpriseAdministratorConnection


type EnterpriseAdministratorEdge
    = EnterpriseAdministratorEdge


type EnterpriseAdministratorInvitation
    = EnterpriseAdministratorInvitation


type EnterpriseAdministratorInvitationConnection
    = EnterpriseAdministratorInvitationConnection


type EnterpriseAdministratorInvitationEdge
    = EnterpriseAdministratorInvitationEdge


type EnterpriseBillingInfo
    = EnterpriseBillingInfo


type EnterpriseIdentityProvider
    = EnterpriseIdentityProvider


type EnterpriseMemberConnection
    = EnterpriseMemberConnection


type EnterpriseMemberEdge
    = EnterpriseMemberEdge


type EnterpriseOrganizationMembershipConnection
    = EnterpriseOrganizationMembershipConnection


type EnterpriseOrganizationMembershipEdge
    = EnterpriseOrganizationMembershipEdge


type EnterpriseOutsideCollaboratorConnection
    = EnterpriseOutsideCollaboratorConnection


type EnterpriseOutsideCollaboratorEdge
    = EnterpriseOutsideCollaboratorEdge


type EnterpriseOwnerInfo
    = EnterpriseOwnerInfo


type EnterprisePendingMemberInvitationConnection
    = EnterprisePendingMemberInvitationConnection


type EnterprisePendingMemberInvitationEdge
    = EnterprisePendingMemberInvitationEdge


type EnterpriseRepositoryInfo
    = EnterpriseRepositoryInfo


type EnterpriseRepositoryInfoConnection
    = EnterpriseRepositoryInfoConnection


type EnterpriseRepositoryInfoEdge
    = EnterpriseRepositoryInfoEdge


type EnterpriseServerInstallation
    = EnterpriseServerInstallation


type EnterpriseServerInstallationConnection
    = EnterpriseServerInstallationConnection


type EnterpriseServerInstallationEdge
    = EnterpriseServerInstallationEdge


type EnterpriseServerUserAccount
    = EnterpriseServerUserAccount


type EnterpriseServerUserAccountConnection
    = EnterpriseServerUserAccountConnection


type EnterpriseServerUserAccountEdge
    = EnterpriseServerUserAccountEdge


type EnterpriseServerUserAccountEmail
    = EnterpriseServerUserAccountEmail


type EnterpriseServerUserAccountEmailConnection
    = EnterpriseServerUserAccountEmailConnection


type EnterpriseServerUserAccountEmailEdge
    = EnterpriseServerUserAccountEmailEdge


type EnterpriseServerUserAccountsUpload
    = EnterpriseServerUserAccountsUpload


type EnterpriseServerUserAccountsUploadConnection
    = EnterpriseServerUserAccountsUploadConnection


type EnterpriseServerUserAccountsUploadEdge
    = EnterpriseServerUserAccountsUploadEdge


type EnterpriseUserAccount
    = EnterpriseUserAccount


type Environment
    = Environment


type EnvironmentConnection
    = EnvironmentConnection


type EnvironmentEdge
    = EnvironmentEdge


type ExternalIdentity
    = ExternalIdentity


type ExternalIdentityAttribute
    = ExternalIdentityAttribute


type ExternalIdentityConnection
    = ExternalIdentityConnection


type ExternalIdentityEdge
    = ExternalIdentityEdge


type ExternalIdentitySamlAttributes
    = ExternalIdentitySamlAttributes


type ExternalIdentityScimAttributes
    = ExternalIdentityScimAttributes


type FollowOrganizationPayload
    = FollowOrganizationPayload


type FollowUserPayload
    = FollowUserPayload


type FollowerConnection
    = FollowerConnection


type FollowingConnection
    = FollowingConnection


type FundingLink
    = FundingLink


type GenericHovercardContext
    = GenericHovercardContext


type Gist
    = Gist


type GistComment
    = GistComment


type GistCommentConnection
    = GistCommentConnection


type GistCommentEdge
    = GistCommentEdge


type GistConnection
    = GistConnection


type GistEdge
    = GistEdge


type GistFile
    = GistFile


type GitActor
    = GitActor


type GitActorConnection
    = GitActorConnection


type GitActorEdge
    = GitActorEdge


type GitHubMetadata
    = GitHubMetadata


type GpgSignature
    = GpgSignature


type GrantEnterpriseOrganizationsMigratorRolePayload
    = GrantEnterpriseOrganizationsMigratorRolePayload


type GrantMigratorRolePayload
    = GrantMigratorRolePayload


type HeadRefDeletedEvent
    = HeadRefDeletedEvent


type HeadRefForcePushedEvent
    = HeadRefForcePushedEvent


type HeadRefRestoredEvent
    = HeadRefRestoredEvent


type Hovercard
    = Hovercard


type InviteEnterpriseAdminPayload
    = InviteEnterpriseAdminPayload


type IpAllowListEntry
    = IpAllowListEntry


type IpAllowListEntryConnection
    = IpAllowListEntryConnection


type IpAllowListEntryEdge
    = IpAllowListEntryEdge


type Issue
    = Issue


type IssueComment
    = IssueComment


type IssueCommentConnection
    = IssueCommentConnection


type IssueCommentEdge
    = IssueCommentEdge


type IssueConnection
    = IssueConnection


type IssueContributionsByRepository
    = IssueContributionsByRepository


type IssueEdge
    = IssueEdge


type IssueTemplate
    = IssueTemplate


type IssueTimelineConnection
    = IssueTimelineConnection


type IssueTimelineItemEdge
    = IssueTimelineItemEdge


type IssueTimelineItemsConnection
    = IssueTimelineItemsConnection


type IssueTimelineItemsEdge
    = IssueTimelineItemsEdge


type JoinedGitHubContribution
    = JoinedGitHubContribution


type Label
    = Label


type LabelConnection
    = LabelConnection


type LabelEdge
    = LabelEdge


type LabeledEvent
    = LabeledEvent


type Language
    = Language


type LanguageConnection
    = LanguageConnection


type LanguageEdge
    = LanguageEdge


type License
    = License


type LicenseRule
    = LicenseRule


type LinkRepositoryToProjectPayload
    = LinkRepositoryToProjectPayload


type LinkedBranch
    = LinkedBranch


type LinkedBranchConnection
    = LinkedBranchConnection


type LinkedBranchEdge
    = LinkedBranchEdge


type LockLockablePayload
    = LockLockablePayload


type LockedEvent
    = LockedEvent


type Mannequin
    = Mannequin


type MarkDiscussionCommentAsAnswerPayload
    = MarkDiscussionCommentAsAnswerPayload


type MarkFileAsViewedPayload
    = MarkFileAsViewedPayload


type MarkPullRequestReadyForReviewPayload
    = MarkPullRequestReadyForReviewPayload


type MarkedAsDuplicateEvent
    = MarkedAsDuplicateEvent


type MarketplaceCategory
    = MarketplaceCategory


type MarketplaceListing
    = MarketplaceListing


type MarketplaceListingConnection
    = MarketplaceListingConnection


type MarketplaceListingEdge
    = MarketplaceListingEdge


type MembersCanDeleteReposClearAuditEntry
    = MembersCanDeleteReposClearAuditEntry


type MembersCanDeleteReposDisableAuditEntry
    = MembersCanDeleteReposDisableAuditEntry


type MembersCanDeleteReposEnableAuditEntry
    = MembersCanDeleteReposEnableAuditEntry


type MentionedEvent
    = MentionedEvent


type MergeBranchPayload
    = MergeBranchPayload


type MergePullRequestPayload
    = MergePullRequestPayload


type MergedEvent
    = MergedEvent


type MigrationSource
    = MigrationSource


type Milestone
    = Milestone


type MilestoneConnection
    = MilestoneConnection


type MilestoneEdge
    = MilestoneEdge


type MilestonedEvent
    = MilestonedEvent


type MinimizeCommentPayload
    = MinimizeCommentPayload


type MoveProjectCardPayload
    = MoveProjectCardPayload


type MoveProjectColumnPayload
    = MoveProjectColumnPayload


type MovedColumnsInProjectEvent
    = MovedColumnsInProjectEvent


type OIDCProvider
    = OIDCProvider


type OauthApplicationCreateAuditEntry
    = OauthApplicationCreateAuditEntry


type OrgAddBillingManagerAuditEntry
    = OrgAddBillingManagerAuditEntry


type OrgAddMemberAuditEntry
    = OrgAddMemberAuditEntry


type OrgBlockUserAuditEntry
    = OrgBlockUserAuditEntry


type OrgConfigDisableCollaboratorsOnlyAuditEntry
    = OrgConfigDisableCollaboratorsOnlyAuditEntry


type OrgConfigEnableCollaboratorsOnlyAuditEntry
    = OrgConfigEnableCollaboratorsOnlyAuditEntry


type OrgCreateAuditEntry
    = OrgCreateAuditEntry


type OrgDisableOauthAppRestrictionsAuditEntry
    = OrgDisableOauthAppRestrictionsAuditEntry


type OrgDisableSamlAuditEntry
    = OrgDisableSamlAuditEntry


type OrgDisableTwoFactorRequirementAuditEntry
    = OrgDisableTwoFactorRequirementAuditEntry


type OrgEnableOauthAppRestrictionsAuditEntry
    = OrgEnableOauthAppRestrictionsAuditEntry


type OrgEnableSamlAuditEntry
    = OrgEnableSamlAuditEntry


type OrgEnableTwoFactorRequirementAuditEntry
    = OrgEnableTwoFactorRequirementAuditEntry


type OrgInviteMemberAuditEntry
    = OrgInviteMemberAuditEntry


type OrgInviteToBusinessAuditEntry
    = OrgInviteToBusinessAuditEntry


type OrgOauthAppAccessApprovedAuditEntry
    = OrgOauthAppAccessApprovedAuditEntry


type OrgOauthAppAccessDeniedAuditEntry
    = OrgOauthAppAccessDeniedAuditEntry


type OrgOauthAppAccessRequestedAuditEntry
    = OrgOauthAppAccessRequestedAuditEntry


type OrgRemoveBillingManagerAuditEntry
    = OrgRemoveBillingManagerAuditEntry


type OrgRemoveMemberAuditEntry
    = OrgRemoveMemberAuditEntry


type OrgRemoveOutsideCollaboratorAuditEntry
    = OrgRemoveOutsideCollaboratorAuditEntry


type OrgRestoreMemberAuditEntry
    = OrgRestoreMemberAuditEntry


type OrgRestoreMemberMembershipOrganizationAuditEntryData
    = OrgRestoreMemberMembershipOrganizationAuditEntryData


type OrgRestoreMemberMembershipRepositoryAuditEntryData
    = OrgRestoreMemberMembershipRepositoryAuditEntryData


type OrgRestoreMemberMembershipTeamAuditEntryData
    = OrgRestoreMemberMembershipTeamAuditEntryData


type OrgUnblockUserAuditEntry
    = OrgUnblockUserAuditEntry


type OrgUpdateDefaultRepositoryPermissionAuditEntry
    = OrgUpdateDefaultRepositoryPermissionAuditEntry


type OrgUpdateMemberAuditEntry
    = OrgUpdateMemberAuditEntry


type OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    = OrgUpdateMemberRepositoryCreationPermissionAuditEntry


type OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    = OrgUpdateMemberRepositoryInvitationPermissionAuditEntry


type Organization
    = Organization


type OrganizationAuditEntryConnection
    = OrganizationAuditEntryConnection


type OrganizationAuditEntryEdge
    = OrganizationAuditEntryEdge


type OrganizationConnection
    = OrganizationConnection


type OrganizationEdge
    = OrganizationEdge


type OrganizationEnterpriseOwnerConnection
    = OrganizationEnterpriseOwnerConnection


type OrganizationEnterpriseOwnerEdge
    = OrganizationEnterpriseOwnerEdge


type OrganizationIdentityProvider
    = OrganizationIdentityProvider


type OrganizationInvitation
    = OrganizationInvitation


type OrganizationInvitationConnection
    = OrganizationInvitationConnection


type OrganizationInvitationEdge
    = OrganizationInvitationEdge


type OrganizationMemberConnection
    = OrganizationMemberConnection


type OrganizationMemberEdge
    = OrganizationMemberEdge


type OrganizationTeamsHovercardContext
    = OrganizationTeamsHovercardContext


type OrganizationsHovercardContext
    = OrganizationsHovercardContext


type Package
    = Package


type PackageConnection
    = PackageConnection


type PackageEdge
    = PackageEdge


type PackageFile
    = PackageFile


type PackageFileConnection
    = PackageFileConnection


type PackageFileEdge
    = PackageFileEdge


type PackageStatistics
    = PackageStatistics


type PackageTag
    = PackageTag


type PackageVersion
    = PackageVersion


type PackageVersionConnection
    = PackageVersionConnection


type PackageVersionEdge
    = PackageVersionEdge


type PackageVersionStatistics
    = PackageVersionStatistics


type PageInfo
    = PageInfo


type PermissionSource
    = PermissionSource


type PinIssuePayload
    = PinIssuePayload


type PinnableItemConnection
    = PinnableItemConnection


type PinnableItemEdge
    = PinnableItemEdge


type PinnedDiscussion
    = PinnedDiscussion


type PinnedDiscussionConnection
    = PinnedDiscussionConnection


type PinnedDiscussionEdge
    = PinnedDiscussionEdge


type PinnedEvent
    = PinnedEvent


type PinnedIssue
    = PinnedIssue


type PinnedIssueConnection
    = PinnedIssueConnection


type PinnedIssueEdge
    = PinnedIssueEdge


type PrivateRepositoryForkingDisableAuditEntry
    = PrivateRepositoryForkingDisableAuditEntry


type PrivateRepositoryForkingEnableAuditEntry
    = PrivateRepositoryForkingEnableAuditEntry


type ProfileItemShowcase
    = ProfileItemShowcase


type Project
    = Project


type ProjectCard
    = ProjectCard


type ProjectCardConnection
    = ProjectCardConnection


type ProjectCardEdge
    = ProjectCardEdge


type ProjectColumn
    = ProjectColumn


type ProjectColumnConnection
    = ProjectColumnConnection


type ProjectColumnEdge
    = ProjectColumnEdge


type ProjectConnection
    = ProjectConnection


type ProjectEdge
    = ProjectEdge


type ProjectNext
    = ProjectNext


type ProjectNextConnection
    = ProjectNextConnection


type ProjectNextEdge
    = ProjectNextEdge


type ProjectNextField
    = ProjectNextField


type ProjectNextFieldConnection
    = ProjectNextFieldConnection


type ProjectNextFieldEdge
    = ProjectNextFieldEdge


type ProjectNextItem
    = ProjectNextItem


type ProjectNextItemConnection
    = ProjectNextItemConnection


type ProjectNextItemEdge
    = ProjectNextItemEdge


type ProjectNextItemFieldValue
    = ProjectNextItemFieldValue


type ProjectNextItemFieldValueConnection
    = ProjectNextItemFieldValueConnection


type ProjectNextItemFieldValueEdge
    = ProjectNextItemFieldValueEdge


type ProjectProgress
    = ProjectProgress


type ProjectV2
    = ProjectV2


type ProjectV2Connection
    = ProjectV2Connection


type ProjectV2Edge
    = ProjectV2Edge


type ProjectV2Field
    = ProjectV2Field


type ProjectV2FieldConfigurationConnection
    = ProjectV2FieldConfigurationConnection


type ProjectV2FieldConfigurationEdge
    = ProjectV2FieldConfigurationEdge


type ProjectV2FieldConnection
    = ProjectV2FieldConnection


type ProjectV2FieldEdge
    = ProjectV2FieldEdge


type ProjectV2Item
    = ProjectV2Item


type ProjectV2ItemConnection
    = ProjectV2ItemConnection


type ProjectV2ItemEdge
    = ProjectV2ItemEdge


type ProjectV2ItemFieldDateValue
    = ProjectV2ItemFieldDateValue


type ProjectV2ItemFieldIterationValue
    = ProjectV2ItemFieldIterationValue


type ProjectV2ItemFieldLabelValue
    = ProjectV2ItemFieldLabelValue


type ProjectV2ItemFieldMilestoneValue
    = ProjectV2ItemFieldMilestoneValue


type ProjectV2ItemFieldNumberValue
    = ProjectV2ItemFieldNumberValue


type ProjectV2ItemFieldPullRequestValue
    = ProjectV2ItemFieldPullRequestValue


type ProjectV2ItemFieldRepositoryValue
    = ProjectV2ItemFieldRepositoryValue


type ProjectV2ItemFieldReviewerValue
    = ProjectV2ItemFieldReviewerValue


type ProjectV2ItemFieldSingleSelectValue
    = ProjectV2ItemFieldSingleSelectValue


type ProjectV2ItemFieldTextValue
    = ProjectV2ItemFieldTextValue


type ProjectV2ItemFieldUserValue
    = ProjectV2ItemFieldUserValue


type ProjectV2ItemFieldValueConnection
    = ProjectV2ItemFieldValueConnection


type ProjectV2ItemFieldValueEdge
    = ProjectV2ItemFieldValueEdge


type ProjectV2IterationField
    = ProjectV2IterationField


type ProjectV2IterationFieldConfiguration
    = ProjectV2IterationFieldConfiguration


type ProjectV2IterationFieldIteration
    = ProjectV2IterationFieldIteration


type ProjectV2SingleSelectField
    = ProjectV2SingleSelectField


type ProjectV2SingleSelectFieldOption
    = ProjectV2SingleSelectFieldOption


type ProjectV2SortBy
    = ProjectV2SortBy


type ProjectV2SortByConnection
    = ProjectV2SortByConnection


type ProjectV2SortByEdge
    = ProjectV2SortByEdge


type ProjectV2SortByField
    = ProjectV2SortByField


type ProjectV2SortByFieldConnection
    = ProjectV2SortByFieldConnection


type ProjectV2SortByFieldEdge
    = ProjectV2SortByFieldEdge


type ProjectV2View
    = ProjectV2View


type ProjectV2ViewConnection
    = ProjectV2ViewConnection


type ProjectV2ViewEdge
    = ProjectV2ViewEdge


type ProjectView
    = ProjectView


type ProjectViewConnection
    = ProjectViewConnection


type ProjectViewEdge
    = ProjectViewEdge


type PublicKey
    = PublicKey


type PublicKeyConnection
    = PublicKeyConnection


type PublicKeyEdge
    = PublicKeyEdge


type PullRequest
    = PullRequest


type PullRequestChangedFile
    = PullRequestChangedFile


type PullRequestChangedFileConnection
    = PullRequestChangedFileConnection


type PullRequestChangedFileEdge
    = PullRequestChangedFileEdge


type PullRequestCommit
    = PullRequestCommit


type PullRequestCommitCommentThread
    = PullRequestCommitCommentThread


type PullRequestCommitConnection
    = PullRequestCommitConnection


type PullRequestCommitEdge
    = PullRequestCommitEdge


type PullRequestConnection
    = PullRequestConnection


type PullRequestContributionsByRepository
    = PullRequestContributionsByRepository


type PullRequestEdge
    = PullRequestEdge


type PullRequestReview
    = PullRequestReview


type PullRequestReviewComment
    = PullRequestReviewComment


type PullRequestReviewCommentConnection
    = PullRequestReviewCommentConnection


type PullRequestReviewCommentEdge
    = PullRequestReviewCommentEdge


type PullRequestReviewConnection
    = PullRequestReviewConnection


type PullRequestReviewContributionsByRepository
    = PullRequestReviewContributionsByRepository


type PullRequestReviewEdge
    = PullRequestReviewEdge


type PullRequestReviewThread
    = PullRequestReviewThread


type PullRequestReviewThreadConnection
    = PullRequestReviewThreadConnection


type PullRequestReviewThreadEdge
    = PullRequestReviewThreadEdge


type PullRequestRevisionMarker
    = PullRequestRevisionMarker


type PullRequestTemplate
    = PullRequestTemplate


type PullRequestThread
    = PullRequestThread


type PullRequestTimelineConnection
    = PullRequestTimelineConnection


type PullRequestTimelineItemEdge
    = PullRequestTimelineItemEdge


type PullRequestTimelineItemsConnection
    = PullRequestTimelineItemsConnection


type PullRequestTimelineItemsEdge
    = PullRequestTimelineItemsEdge


type Push
    = Push


type PushAllowance
    = PushAllowance


type PushAllowanceConnection
    = PushAllowanceConnection


type PushAllowanceEdge
    = PushAllowanceEdge


type RateLimit
    = RateLimit


type ReactingUserConnection
    = ReactingUserConnection


type ReactingUserEdge
    = ReactingUserEdge


type Reaction
    = Reaction


type ReactionConnection
    = ReactionConnection


type ReactionEdge
    = ReactionEdge


type ReactionGroup
    = ReactionGroup


type ReactorConnection
    = ReactorConnection


type ReactorEdge
    = ReactorEdge


type ReadyForReviewEvent
    = ReadyForReviewEvent


type Ref
    = Ref


type RefConnection
    = RefConnection


type RefEdge
    = RefEdge


type RefUpdateRule
    = RefUpdateRule


type ReferencedEvent
    = ReferencedEvent


type RegenerateEnterpriseIdentityProviderRecoveryCodesPayload
    = RegenerateEnterpriseIdentityProviderRecoveryCodesPayload


type RegenerateVerifiableDomainTokenPayload
    = RegenerateVerifiableDomainTokenPayload


type RejectDeploymentsPayload
    = RejectDeploymentsPayload


type Release
    = Release


type ReleaseAsset
    = ReleaseAsset


type ReleaseAssetConnection
    = ReleaseAssetConnection


type ReleaseAssetEdge
    = ReleaseAssetEdge


type ReleaseConnection
    = ReleaseConnection


type ReleaseEdge
    = ReleaseEdge


type RemoveAssigneesFromAssignablePayload
    = RemoveAssigneesFromAssignablePayload


type RemoveEnterpriseAdminPayload
    = RemoveEnterpriseAdminPayload


type RemoveEnterpriseIdentityProviderPayload
    = RemoveEnterpriseIdentityProviderPayload


type RemoveEnterpriseOrganizationPayload
    = RemoveEnterpriseOrganizationPayload


type RemoveEnterpriseSupportEntitlementPayload
    = RemoveEnterpriseSupportEntitlementPayload


type RemoveLabelsFromLabelablePayload
    = RemoveLabelsFromLabelablePayload


type RemoveOutsideCollaboratorPayload
    = RemoveOutsideCollaboratorPayload


type RemoveReactionPayload
    = RemoveReactionPayload


type RemoveStarPayload
    = RemoveStarPayload


type RemoveUpvotePayload
    = RemoveUpvotePayload


type RemovedFromProjectEvent
    = RemovedFromProjectEvent


type RenamedTitleEvent
    = RenamedTitleEvent


type ReopenIssuePayload
    = ReopenIssuePayload


type ReopenPullRequestPayload
    = ReopenPullRequestPayload


type ReopenedEvent
    = ReopenedEvent


type RepoAccessAuditEntry
    = RepoAccessAuditEntry


type RepoAddMemberAuditEntry
    = RepoAddMemberAuditEntry


type RepoAddTopicAuditEntry
    = RepoAddTopicAuditEntry


type RepoArchivedAuditEntry
    = RepoArchivedAuditEntry


type RepoChangeMergeSettingAuditEntry
    = RepoChangeMergeSettingAuditEntry


type RepoConfigDisableAnonymousGitAccessAuditEntry
    = RepoConfigDisableAnonymousGitAccessAuditEntry


type RepoConfigDisableCollaboratorsOnlyAuditEntry
    = RepoConfigDisableCollaboratorsOnlyAuditEntry


type RepoConfigDisableContributorsOnlyAuditEntry
    = RepoConfigDisableContributorsOnlyAuditEntry


type RepoConfigDisableSockpuppetDisallowedAuditEntry
    = RepoConfigDisableSockpuppetDisallowedAuditEntry


type RepoConfigEnableAnonymousGitAccessAuditEntry
    = RepoConfigEnableAnonymousGitAccessAuditEntry


type RepoConfigEnableCollaboratorsOnlyAuditEntry
    = RepoConfigEnableCollaboratorsOnlyAuditEntry


type RepoConfigEnableContributorsOnlyAuditEntry
    = RepoConfigEnableContributorsOnlyAuditEntry


type RepoConfigEnableSockpuppetDisallowedAuditEntry
    = RepoConfigEnableSockpuppetDisallowedAuditEntry


type RepoConfigLockAnonymousGitAccessAuditEntry
    = RepoConfigLockAnonymousGitAccessAuditEntry


type RepoConfigUnlockAnonymousGitAccessAuditEntry
    = RepoConfigUnlockAnonymousGitAccessAuditEntry


type RepoCreateAuditEntry
    = RepoCreateAuditEntry


type RepoDestroyAuditEntry
    = RepoDestroyAuditEntry


type RepoRemoveMemberAuditEntry
    = RepoRemoveMemberAuditEntry


type RepoRemoveTopicAuditEntry
    = RepoRemoveTopicAuditEntry


type Repository
    = Repository


type RepositoryCodeowners
    = RepositoryCodeowners


type RepositoryCodeownersError
    = RepositoryCodeownersError


type RepositoryCollaboratorConnection
    = RepositoryCollaboratorConnection


type RepositoryCollaboratorEdge
    = RepositoryCollaboratorEdge


type RepositoryConnection
    = RepositoryConnection


type RepositoryContactLink
    = RepositoryContactLink


type RepositoryEdge
    = RepositoryEdge


type RepositoryInteractionAbility
    = RepositoryInteractionAbility


type RepositoryInvitation
    = RepositoryInvitation


type RepositoryInvitationConnection
    = RepositoryInvitationConnection


type RepositoryInvitationEdge
    = RepositoryInvitationEdge


type RepositoryMigration
    = RepositoryMigration


type RepositoryMigrationConnection
    = RepositoryMigrationConnection


type RepositoryMigrationEdge
    = RepositoryMigrationEdge


type RepositoryTopic
    = RepositoryTopic


type RepositoryTopicConnection
    = RepositoryTopicConnection


type RepositoryTopicEdge
    = RepositoryTopicEdge


type RepositoryVisibilityChangeDisableAuditEntry
    = RepositoryVisibilityChangeDisableAuditEntry


type RepositoryVisibilityChangeEnableAuditEntry
    = RepositoryVisibilityChangeEnableAuditEntry


type RepositoryVulnerabilityAlert
    = RepositoryVulnerabilityAlert


type RepositoryVulnerabilityAlertConnection
    = RepositoryVulnerabilityAlertConnection


type RepositoryVulnerabilityAlertEdge
    = RepositoryVulnerabilityAlertEdge


type RequestReviewsPayload
    = RequestReviewsPayload


type RequestedReviewerConnection
    = RequestedReviewerConnection


type RequestedReviewerEdge
    = RequestedReviewerEdge


type RequiredStatusCheckDescription
    = RequiredStatusCheckDescription


type RerequestCheckSuitePayload
    = RerequestCheckSuitePayload


type ResolveReviewThreadPayload
    = ResolveReviewThreadPayload


type RestrictedContribution
    = RestrictedContribution


type ReviewDismissalAllowance
    = ReviewDismissalAllowance


type ReviewDismissalAllowanceConnection
    = ReviewDismissalAllowanceConnection


type ReviewDismissalAllowanceEdge
    = ReviewDismissalAllowanceEdge


type ReviewDismissedEvent
    = ReviewDismissedEvent


type ReviewRequest
    = ReviewRequest


type ReviewRequestConnection
    = ReviewRequestConnection


type ReviewRequestEdge
    = ReviewRequestEdge


type ReviewRequestRemovedEvent
    = ReviewRequestRemovedEvent


type ReviewRequestedEvent
    = ReviewRequestedEvent


type ReviewStatusHovercardContext
    = ReviewStatusHovercardContext


type RevokeEnterpriseOrganizationsMigratorRolePayload
    = RevokeEnterpriseOrganizationsMigratorRolePayload


type RevokeMigratorRolePayload
    = RevokeMigratorRolePayload


type SavedReply
    = SavedReply


type SavedReplyConnection
    = SavedReplyConnection


type SavedReplyEdge
    = SavedReplyEdge


type SearchResultItemConnection
    = SearchResultItemConnection


type SearchResultItemEdge
    = SearchResultItemEdge


type SecurityAdvisory
    = SecurityAdvisory


type SecurityAdvisoryConnection
    = SecurityAdvisoryConnection


type SecurityAdvisoryEdge
    = SecurityAdvisoryEdge


type SecurityAdvisoryIdentifier
    = SecurityAdvisoryIdentifier


type SecurityAdvisoryPackage
    = SecurityAdvisoryPackage


type SecurityAdvisoryPackageVersion
    = SecurityAdvisoryPackageVersion


type SecurityAdvisoryReference
    = SecurityAdvisoryReference


type SecurityVulnerability
    = SecurityVulnerability


type SecurityVulnerabilityConnection
    = SecurityVulnerabilityConnection


type SecurityVulnerabilityEdge
    = SecurityVulnerabilityEdge


type SetEnterpriseIdentityProviderPayload
    = SetEnterpriseIdentityProviderPayload


type SetOrganizationInteractionLimitPayload
    = SetOrganizationInteractionLimitPayload


type SetRepositoryInteractionLimitPayload
    = SetRepositoryInteractionLimitPayload


type SetUserInteractionLimitPayload
    = SetUserInteractionLimitPayload


type SmimeSignature
    = SmimeSignature


type SortBy
    = SortBy


type SponsorConnection
    = SponsorConnection


type SponsorEdge
    = SponsorEdge


type SponsorableItemConnection
    = SponsorableItemConnection


type SponsorableItemEdge
    = SponsorableItemEdge


type SponsorsActivity
    = SponsorsActivity


type SponsorsActivityConnection
    = SponsorsActivityConnection


type SponsorsActivityEdge
    = SponsorsActivityEdge


type SponsorsGoal
    = SponsorsGoal


type SponsorsListing
    = SponsorsListing


type SponsorsTier
    = SponsorsTier


type SponsorsTierAdminInfo
    = SponsorsTierAdminInfo


type SponsorsTierConnection
    = SponsorsTierConnection


type SponsorsTierEdge
    = SponsorsTierEdge


type Sponsorship
    = Sponsorship


type SponsorshipConnection
    = SponsorshipConnection


type SponsorshipEdge
    = SponsorshipEdge


type SponsorshipNewsletter
    = SponsorshipNewsletter


type SponsorshipNewsletterConnection
    = SponsorshipNewsletterConnection


type SponsorshipNewsletterEdge
    = SponsorshipNewsletterEdge


type SshSignature
    = SshSignature


type StargazerConnection
    = StargazerConnection


type StargazerEdge
    = StargazerEdge


type StarredRepositoryConnection
    = StarredRepositoryConnection


type StarredRepositoryEdge
    = StarredRepositoryEdge


type StartRepositoryMigrationPayload
    = StartRepositoryMigrationPayload


type Status
    = Status


type StatusCheckRollup
    = StatusCheckRollup


type StatusCheckRollupContextConnection
    = StatusCheckRollupContextConnection


type StatusCheckRollupContextEdge
    = StatusCheckRollupContextEdge


type StatusContext
    = StatusContext


type StatusContextStateCount
    = StatusContextStateCount


type SubmitPullRequestReviewPayload
    = SubmitPullRequestReviewPayload


type Submodule
    = Submodule


type SubmoduleConnection
    = SubmoduleConnection


type SubmoduleEdge
    = SubmoduleEdge


type SubscribedEvent
    = SubscribedEvent


type SuggestedReviewer
    = SuggestedReviewer


type Tag
    = Tag


type Team
    = Team


type TeamAddMemberAuditEntry
    = TeamAddMemberAuditEntry


type TeamAddRepositoryAuditEntry
    = TeamAddRepositoryAuditEntry


type TeamChangeParentTeamAuditEntry
    = TeamChangeParentTeamAuditEntry


type TeamConnection
    = TeamConnection


type TeamDiscussion
    = TeamDiscussion


type TeamDiscussionComment
    = TeamDiscussionComment


type TeamDiscussionCommentConnection
    = TeamDiscussionCommentConnection


type TeamDiscussionCommentEdge
    = TeamDiscussionCommentEdge


type TeamDiscussionConnection
    = TeamDiscussionConnection


type TeamDiscussionEdge
    = TeamDiscussionEdge


type TeamEdge
    = TeamEdge


type TeamMemberConnection
    = TeamMemberConnection


type TeamMemberEdge
    = TeamMemberEdge


type TeamRemoveMemberAuditEntry
    = TeamRemoveMemberAuditEntry


type TeamRemoveRepositoryAuditEntry
    = TeamRemoveRepositoryAuditEntry


type TeamRepositoryConnection
    = TeamRepositoryConnection


type TeamRepositoryEdge
    = TeamRepositoryEdge


type TextMatch
    = TextMatch


type TextMatchHighlight
    = TextMatchHighlight


type Topic
    = Topic


type TransferIssuePayload
    = TransferIssuePayload


type TransferredEvent
    = TransferredEvent


type Tree
    = Tree


type TreeEntry
    = TreeEntry


type UnarchiveRepositoryPayload
    = UnarchiveRepositoryPayload


type UnassignedEvent
    = UnassignedEvent


type UnfollowOrganizationPayload
    = UnfollowOrganizationPayload


type UnfollowUserPayload
    = UnfollowUserPayload


type UnknownSignature
    = UnknownSignature


type UnlabeledEvent
    = UnlabeledEvent


type UnlinkRepositoryFromProjectPayload
    = UnlinkRepositoryFromProjectPayload


type UnlockLockablePayload
    = UnlockLockablePayload


type UnlockedEvent
    = UnlockedEvent


type UnmarkDiscussionCommentAsAnswerPayload
    = UnmarkDiscussionCommentAsAnswerPayload


type UnmarkFileAsViewedPayload
    = UnmarkFileAsViewedPayload


type UnmarkIssueAsDuplicatePayload
    = UnmarkIssueAsDuplicatePayload


type UnmarkedAsDuplicateEvent
    = UnmarkedAsDuplicateEvent


type UnminimizeCommentPayload
    = UnminimizeCommentPayload


type UnpinIssuePayload
    = UnpinIssuePayload


type UnpinnedEvent
    = UnpinnedEvent


type UnresolveReviewThreadPayload
    = UnresolveReviewThreadPayload


type UnsubscribedEvent
    = UnsubscribedEvent


type UpdateBranchProtectionRulePayload
    = UpdateBranchProtectionRulePayload


type UpdateCheckRunPayload
    = UpdateCheckRunPayload


type UpdateCheckSuitePreferencesPayload
    = UpdateCheckSuitePreferencesPayload


type UpdateDiscussionCommentPayload
    = UpdateDiscussionCommentPayload


type UpdateDiscussionPayload
    = UpdateDiscussionPayload


type UpdateEnterpriseAdministratorRolePayload
    = UpdateEnterpriseAdministratorRolePayload


type UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload
    = UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload


type UpdateEnterpriseDefaultRepositoryPermissionSettingPayload
    = UpdateEnterpriseDefaultRepositoryPermissionSettingPayload


type UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload
    = UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload


type UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload
    = UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload


type UpdateEnterpriseMembersCanDeleteIssuesSettingPayload
    = UpdateEnterpriseMembersCanDeleteIssuesSettingPayload


type UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload
    = UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload


type UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload
    = UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload


type UpdateEnterpriseMembersCanMakePurchasesSettingPayload
    = UpdateEnterpriseMembersCanMakePurchasesSettingPayload


type UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload
    = UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload


type UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload
    = UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload


type UpdateEnterpriseOrganizationProjectsSettingPayload
    = UpdateEnterpriseOrganizationProjectsSettingPayload


type UpdateEnterpriseOwnerOrganizationRolePayload
    = UpdateEnterpriseOwnerOrganizationRolePayload


type UpdateEnterpriseProfilePayload
    = UpdateEnterpriseProfilePayload


type UpdateEnterpriseRepositoryProjectsSettingPayload
    = UpdateEnterpriseRepositoryProjectsSettingPayload


type UpdateEnterpriseTeamDiscussionsSettingPayload
    = UpdateEnterpriseTeamDiscussionsSettingPayload


type UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload
    = UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload


type UpdateEnvironmentPayload
    = UpdateEnvironmentPayload


type UpdateIpAllowListEnabledSettingPayload
    = UpdateIpAllowListEnabledSettingPayload


type UpdateIpAllowListEntryPayload
    = UpdateIpAllowListEntryPayload


type UpdateIpAllowListForInstalledAppsEnabledSettingPayload
    = UpdateIpAllowListForInstalledAppsEnabledSettingPayload


type UpdateIssueCommentPayload
    = UpdateIssueCommentPayload


type UpdateIssuePayload
    = UpdateIssuePayload


type UpdateNotificationRestrictionSettingPayload
    = UpdateNotificationRestrictionSettingPayload


type UpdateOrganizationAllowPrivateRepositoryForkingSettingPayload
    = UpdateOrganizationAllowPrivateRepositoryForkingSettingPayload


type UpdateOrganizationWebCommitSignoffSettingPayload
    = UpdateOrganizationWebCommitSignoffSettingPayload


type UpdateProjectCardPayload
    = UpdateProjectCardPayload


type UpdateProjectColumnPayload
    = UpdateProjectColumnPayload


type UpdateProjectDraftIssuePayload
    = UpdateProjectDraftIssuePayload


type UpdateProjectNextItemFieldPayload
    = UpdateProjectNextItemFieldPayload


type UpdateProjectNextPayload
    = UpdateProjectNextPayload


type UpdateProjectPayload
    = UpdateProjectPayload


type UpdateProjectV2DraftIssuePayload
    = UpdateProjectV2DraftIssuePayload


type UpdateProjectV2ItemFieldValuePayload
    = UpdateProjectV2ItemFieldValuePayload


type UpdateProjectV2ItemPositionPayload
    = UpdateProjectV2ItemPositionPayload


type UpdateProjectV2Payload
    = UpdateProjectV2Payload


type UpdatePullRequestBranchPayload
    = UpdatePullRequestBranchPayload


type UpdatePullRequestPayload
    = UpdatePullRequestPayload


type UpdatePullRequestReviewCommentPayload
    = UpdatePullRequestReviewCommentPayload


type UpdatePullRequestReviewPayload
    = UpdatePullRequestReviewPayload


type UpdateRefPayload
    = UpdateRefPayload


type UpdateRepositoryPayload
    = UpdateRepositoryPayload


type UpdateRepositoryWebCommitSignoffSettingPayload
    = UpdateRepositoryWebCommitSignoffSettingPayload


type UpdateSponsorshipPreferencesPayload
    = UpdateSponsorshipPreferencesPayload


type UpdateSubscriptionPayload
    = UpdateSubscriptionPayload


type UpdateTeamDiscussionCommentPayload
    = UpdateTeamDiscussionCommentPayload


type UpdateTeamDiscussionPayload
    = UpdateTeamDiscussionPayload


type UpdateTeamsRepositoryPayload
    = UpdateTeamsRepositoryPayload


type UpdateTopicsPayload
    = UpdateTopicsPayload


type User
    = User


type UserBlockedEvent
    = UserBlockedEvent


type UserConnection
    = UserConnection


type UserContentEdit
    = UserContentEdit


type UserContentEditConnection
    = UserContentEditConnection


type UserContentEditEdge
    = UserContentEditEdge


type UserEdge
    = UserEdge


type UserEmailMetadata
    = UserEmailMetadata


type UserStatus
    = UserStatus


type UserStatusConnection
    = UserStatusConnection


type UserStatusEdge
    = UserStatusEdge


type VerifiableDomain
    = VerifiableDomain


type VerifiableDomainConnection
    = VerifiableDomainConnection


type VerifiableDomainEdge
    = VerifiableDomainEdge


type VerifyVerifiableDomainPayload
    = VerifyVerifiableDomainPayload


type ViewerHovercardContext
    = ViewerHovercardContext


type Workflow
    = Workflow


type WorkflowRun
    = WorkflowRun


type WorkflowRunConnection
    = WorkflowRunConnection


type WorkflowRunEdge
    = WorkflowRunEdge
