-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.BranchProtectionRule exposing (..)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Can this branch be deleted.
-}
allowsDeletions : SelectionSet Bool Github.Object.BranchProtectionRule
allowsDeletions =
    Object.selectionForField "Bool" "allowsDeletions" [] Decode.bool


{-| Are force pushes allowed on this branch.
-}
allowsForcePushes : SelectionSet Bool Github.Object.BranchProtectionRule
allowsForcePushes =
    Object.selectionForField "Bool" "allowsForcePushes" [] Decode.bool


{-| Is branch creation a protected operation.
-}
blocksCreations : SelectionSet Bool Github.Object.BranchProtectionRule
blocksCreations =
    Object.selectionForField "Bool" "blocksCreations" [] Decode.bool


type alias BranchProtectionRuleConflictsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of conflicts matching branches protection rule and other branch protection rules

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
branchProtectionRuleConflicts :
    (BranchProtectionRuleConflictsOptionalArguments -> BranchProtectionRuleConflictsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.BranchProtectionRuleConflictConnection
    -> SelectionSet decodesTo Github.Object.BranchProtectionRule
branchProtectionRuleConflicts fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "branchProtectionRuleConflicts" optionalArgs____ object____ Basics.identity


type alias BypassForcePushAllowancesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of actors able to force push for this branch protection rule.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
bypassForcePushAllowances :
    (BypassForcePushAllowancesOptionalArguments -> BypassForcePushAllowancesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.BypassForcePushAllowanceConnection
    -> SelectionSet decodesTo Github.Object.BranchProtectionRule
bypassForcePushAllowances fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "bypassForcePushAllowances" optionalArgs____ object____ Basics.identity


type alias BypassPullRequestAllowancesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of actors able to bypass PRs for this branch protection rule.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
bypassPullRequestAllowances :
    (BypassPullRequestAllowancesOptionalArguments -> BypassPullRequestAllowancesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.BypassPullRequestAllowanceConnection
    -> SelectionSet decodesTo Github.Object.BranchProtectionRule
bypassPullRequestAllowances fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "bypassPullRequestAllowances" optionalArgs____ object____ Basics.identity


{-| The actor who created this branch protection rule.
-}
creator :
    SelectionSet decodesTo Github.Interface.Actor
    -> SelectionSet (Maybe decodesTo) Github.Object.BranchProtectionRule
creator object____ =
    Object.selectionForCompositeField "creator" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Github.Object.BranchProtectionRule
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| Will new commits pushed to matching branches dismiss pull request review approvals.
-}
dismissesStaleReviews : SelectionSet Bool Github.Object.BranchProtectionRule
dismissesStaleReviews =
    Object.selectionForField "Bool" "dismissesStaleReviews" [] Decode.bool


id : SelectionSet Github.ScalarCodecs.Id Github.Object.BranchProtectionRule
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Can admins overwrite branch protection.
-}
isAdminEnforced : SelectionSet Bool Github.Object.BranchProtectionRule
isAdminEnforced =
    Object.selectionForField "Bool" "isAdminEnforced" [] Decode.bool


{-| Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing.
-}
lockAllowsFetchAndMerge : SelectionSet Bool Github.Object.BranchProtectionRule
lockAllowsFetchAndMerge =
    Object.selectionForField "Bool" "lockAllowsFetchAndMerge" [] Decode.bool


{-| Whether to set the branch as read-only. If this is true, users will not be able to push to the branch.
-}
lockBranch : SelectionSet Bool Github.Object.BranchProtectionRule
lockBranch =
    Object.selectionForField "Bool" "lockBranch" [] Decode.bool


type alias MatchingRefsOptionalArguments =
    { query : OptionalArgument String
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| Repository refs that are protected by this rule

  - query - Filters refs with query on name
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
matchingRefs :
    (MatchingRefsOptionalArguments -> MatchingRefsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.RefConnection
    -> SelectionSet decodesTo Github.Object.BranchProtectionRule
matchingRefs fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { query = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "query" filledInOptionals____.query Encode.string, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "matchingRefs" optionalArgs____ object____ Basics.identity


{-| Identifies the protection rule pattern.
-}
pattern : SelectionSet String Github.Object.BranchProtectionRule
pattern =
    Object.selectionForField "String" "pattern" [] Decode.string


type alias PushAllowancesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list push allowances for this branch protection rule.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
pushAllowances :
    (PushAllowancesOptionalArguments -> PushAllowancesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.PushAllowanceConnection
    -> SelectionSet decodesTo Github.Object.BranchProtectionRule
pushAllowances fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "pushAllowances" optionalArgs____ object____ Basics.identity


{-| The repository associated with this branch protection rule.
-}
repository :
    SelectionSet decodesTo Github.Object.Repository
    -> SelectionSet (Maybe decodesTo) Github.Object.BranchProtectionRule
repository object____ =
    Object.selectionForCompositeField "repository" [] object____ (Basics.identity >> Decode.nullable)


{-| Whether someone other than the person who last pushed to the branch must approve this pull request
-}
requireLastPushApproval : SelectionSet Bool Github.Object.BranchProtectionRule
requireLastPushApproval =
    Object.selectionForField "Bool" "requireLastPushApproval" [] Decode.bool


{-| Number of approving reviews required to update matching branches.
-}
requiredApprovingReviewCount : SelectionSet (Maybe Int) Github.Object.BranchProtectionRule
requiredApprovingReviewCount =
    Object.selectionForField "(Maybe Int)" "requiredApprovingReviewCount" [] (Decode.int |> Decode.nullable)


{-| List of required status check contexts that must pass for commits to be accepted to matching branches.
-}
requiredStatusCheckContexts : SelectionSet (Maybe (List (Maybe String))) Github.Object.BranchProtectionRule
requiredStatusCheckContexts =
    Object.selectionForField "(Maybe (List (Maybe String)))" "requiredStatusCheckContexts" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| List of required status checks that must pass for commits to be accepted to matching branches.
-}
requiredStatusChecks :
    SelectionSet decodesTo Github.Object.RequiredStatusCheckDescription
    -> SelectionSet (Maybe (List decodesTo)) Github.Object.BranchProtectionRule
requiredStatusChecks object____ =
    Object.selectionForCompositeField "requiredStatusChecks" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Are approving reviews required to update matching branches.
-}
requiresApprovingReviews : SelectionSet Bool Github.Object.BranchProtectionRule
requiresApprovingReviews =
    Object.selectionForField "Bool" "requiresApprovingReviews" [] Decode.bool


{-| Are reviews from code owners required to update matching branches.
-}
requiresCodeOwnerReviews : SelectionSet Bool Github.Object.BranchProtectionRule
requiresCodeOwnerReviews =
    Object.selectionForField "Bool" "requiresCodeOwnerReviews" [] Decode.bool


{-| Are commits required to be signed.
-}
requiresCommitSignatures : SelectionSet Bool Github.Object.BranchProtectionRule
requiresCommitSignatures =
    Object.selectionForField "Bool" "requiresCommitSignatures" [] Decode.bool


{-| Are conversations required to be resolved before merging.
-}
requiresConversationResolution : SelectionSet Bool Github.Object.BranchProtectionRule
requiresConversationResolution =
    Object.selectionForField "Bool" "requiresConversationResolution" [] Decode.bool


{-| Are merge commits prohibited from being pushed to this branch.
-}
requiresLinearHistory : SelectionSet Bool Github.Object.BranchProtectionRule
requiresLinearHistory =
    Object.selectionForField "Bool" "requiresLinearHistory" [] Decode.bool


{-| Are status checks required to update matching branches.
-}
requiresStatusChecks : SelectionSet Bool Github.Object.BranchProtectionRule
requiresStatusChecks =
    Object.selectionForField "Bool" "requiresStatusChecks" [] Decode.bool


{-| Are branches required to be up to date before merging.
-}
requiresStrictStatusChecks : SelectionSet Bool Github.Object.BranchProtectionRule
requiresStrictStatusChecks =
    Object.selectionForField "Bool" "requiresStrictStatusChecks" [] Decode.bool


{-| Is pushing to matching branches restricted.
-}
restrictsPushes : SelectionSet Bool Github.Object.BranchProtectionRule
restrictsPushes =
    Object.selectionForField "Bool" "restrictsPushes" [] Decode.bool


{-| Is dismissal of pull request reviews restricted.
-}
restrictsReviewDismissals : SelectionSet Bool Github.Object.BranchProtectionRule
restrictsReviewDismissals =
    Object.selectionForField "Bool" "restrictsReviewDismissals" [] Decode.bool


type alias ReviewDismissalAllowancesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list review dismissal allowances for this branch protection rule.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
reviewDismissalAllowances :
    (ReviewDismissalAllowancesOptionalArguments -> ReviewDismissalAllowancesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.ReviewDismissalAllowanceConnection
    -> SelectionSet decodesTo Github.Object.BranchProtectionRule
reviewDismissalAllowances fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reviewDismissalAllowances" optionalArgs____ object____ Basics.identity
