-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.CheckAnnotationSpan exposing (..)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| End position (inclusive).
-}
end :
    SelectionSet decodesTo Github.Object.CheckAnnotationPosition
    -> SelectionSet decodesTo Github.Object.CheckAnnotationSpan
end object____ =
    Object.selectionForCompositeField "end" [] object____ Basics.identity


{-| Start position (inclusive).
-}
start :
    SelectionSet decodesTo Github.Object.CheckAnnotationPosition
    -> SelectionSet decodesTo Github.Object.CheckAnnotationSpan
start object____ =
    Object.selectionForCompositeField "start" [] object____ Basics.identity
