-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.Cwe exposing (..)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the CWE
-}
cweId : SelectionSet String Github.Object.Cwe
cweId =
    Object.selectionForField "String" "cweId" [] Decode.string


{-| A detailed description of this CWE
-}
description : SelectionSet String Github.Object.Cwe
description =
    Object.selectionForField "String" "description" [] Decode.string


id : SelectionSet Github.ScalarCodecs.Id Github.Object.Cwe
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of this CWE
-}
name : SelectionSet String Github.Object.Cwe
name =
    Object.selectionForField "String" "name" [] Decode.string
