-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.ExternalIdentityScimAttributes exposing (..)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The emails associated with the SCIM identity
-}
emails :
    SelectionSet decodesTo Github.Object.UserEmailMetadata
    -> SelectionSet (Maybe (List decodesTo)) Github.Object.ExternalIdentityScimAttributes
emails object____ =
    Object.selectionForCompositeField "emails" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Family name of the SCIM identity
-}
familyName : SelectionSet (Maybe String) Github.Object.ExternalIdentityScimAttributes
familyName =
    Object.selectionForField "(Maybe String)" "familyName" [] (Decode.string |> Decode.nullable)


{-| Given name of the SCIM identity
-}
givenName : SelectionSet (Maybe String) Github.Object.ExternalIdentityScimAttributes
givenName =
    Object.selectionForField "(Maybe String)" "givenName" [] (Decode.string |> Decode.nullable)


{-| The groups linked to this identity in IDP
-}
groups : SelectionSet (Maybe (List String)) Github.Object.ExternalIdentityScimAttributes
groups =
    Object.selectionForField "(Maybe (List String))" "groups" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| The userName of the SCIM identity
-}
username : SelectionSet (Maybe String) Github.Object.ExternalIdentityScimAttributes
username =
    Object.selectionForField "(Maybe String)" "username" [] (Decode.string |> Decode.nullable)
