-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.OrganizationIdentityProvider exposing (..)

import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The digest algorithm used to sign SAML requests for the Identity Provider.
-}
digestMethod : SelectionSet (Maybe Github.ScalarCodecs.Uri) Github.Object.OrganizationIdentityProvider
digestMethod =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "digestMethod" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)


type alias ExternalIdentitiesOptionalArguments =
    { membersOnly : OptionalArgument Bool
    , login : OptionalArgument String
    , userName : OptionalArgument String
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| External Identities provisioned by this Identity Provider

  - membersOnly - Filter to external identities with valid org membership only
  - login - Filter to external identities with the users login
  - userName - Filter to external identities with the users userName/NameID attribute
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
externalIdentities :
    (ExternalIdentitiesOptionalArguments -> ExternalIdentitiesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.ExternalIdentityConnection
    -> SelectionSet decodesTo Github.Object.OrganizationIdentityProvider
externalIdentities fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { membersOnly = Absent, login = Absent, userName = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "membersOnly" filledInOptionals____.membersOnly Encode.bool, Argument.optional "login" filledInOptionals____.login Encode.string, Argument.optional "userName" filledInOptionals____.userName Encode.string, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "externalIdentities" optionalArgs____ object____ Basics.identity


id : SelectionSet Github.ScalarCodecs.Id Github.Object.OrganizationIdentityProvider
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The x509 certificate used by the Identity Provider to sign assertions and responses.
-}
idpCertificate : SelectionSet (Maybe Github.ScalarCodecs.X509Certificate) Github.Object.OrganizationIdentityProvider
idpCertificate =
    Object.selectionForField "(Maybe ScalarCodecs.X509Certificate)" "idpCertificate" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecX509Certificate |> .decoder |> Decode.nullable)


{-| The Issuer Entity ID for the SAML Identity Provider
-}
issuer : SelectionSet (Maybe String) Github.Object.OrganizationIdentityProvider
issuer =
    Object.selectionForField "(Maybe String)" "issuer" [] (Decode.string |> Decode.nullable)


{-| Organization this Identity Provider belongs to
-}
organization :
    SelectionSet decodesTo Github.Object.Organization
    -> SelectionSet (Maybe decodesTo) Github.Object.OrganizationIdentityProvider
organization object____ =
    Object.selectionForCompositeField "organization" [] object____ (Basics.identity >> Decode.nullable)


{-| The signature algorithm used to sign SAML requests for the Identity Provider.
-}
signatureMethod : SelectionSet (Maybe Github.ScalarCodecs.Uri) Github.Object.OrganizationIdentityProvider
signatureMethod =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "signatureMethod" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)


{-| The URL endpoint for the Identity Provider's SAML SSO.
-}
ssoUrl : SelectionSet (Maybe Github.ScalarCodecs.Uri) Github.Object.OrganizationIdentityProvider
ssoUrl =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "ssoUrl" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)
