-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.SponsorsGoal exposing (..)

import Github.Enum.SponsorsGoalKind
import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A description of the goal from the maintainer.
-}
description : SelectionSet (Maybe String) Github.Object.SponsorsGoal
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| What the objective of this goal is.
-}
kind : SelectionSet Github.Enum.SponsorsGoalKind.SponsorsGoalKind Github.Object.SponsorsGoal
kind =
    Object.selectionForField "Enum.SponsorsGoalKind.SponsorsGoalKind" "kind" [] Github.Enum.SponsorsGoalKind.decoder


{-| The percentage representing how complete this goal is, between 0-100.
-}
percentComplete : SelectionSet Int Github.Object.SponsorsGoal
percentComplete =
    Object.selectionForField "Int" "percentComplete" [] Decode.int


{-| What the goal amount is. Represents an amount in USD for monthly sponsorship amount goals. Represents a count of unique sponsors for total sponsors count goals.
-}
targetValue : SelectionSet Int Github.Object.SponsorsGoal
targetValue =
    Object.selectionForField "Int" "targetValue" [] Decode.int


{-| A brief summary of the kind and target value of this goal.
-}
title : SelectionSet String Github.Object.SponsorsGoal
title =
    Object.selectionForField "String" "title" [] Decode.string
