-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Object.User exposing (..)

import Github.Enum.GistPrivacy
import Github.Enum.IssueState
import Github.Enum.PackageType
import Github.Enum.PinnableItemType
import Github.Enum.ProjectNextOrderField
import Github.Enum.ProjectState
import Github.Enum.PullRequestState
import Github.Enum.RepositoryAffiliation
import Github.Enum.RepositoryContributionType
import Github.Enum.RepositoryPrivacy
import Github.Enum.SponsorsActivityAction
import Github.Enum.SponsorsActivityPeriod
import Github.InputObject
import Github.Interface
import Github.Object
import Github.Scalar
import Github.ScalarCodecs
import Github.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias AnyPinnableItemsOptionalArguments =
    { type_ : OptionalArgument Github.Enum.PinnableItemType.PinnableItemType }


{-| Determine if this repository owner has any items that can be pinned to their profile.

  - type\_ - Filter to only a particular kind of pinnable item.

-}
anyPinnableItems :
    (AnyPinnableItemsOptionalArguments -> AnyPinnableItemsOptionalArguments)
    -> SelectionSet Bool Github.Object.User
anyPinnableItems fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { type_ = Absent }

        optionalArgs____ =
            [ Argument.optional "type" filledInOptionals____.type_ (Encode.enum Github.Enum.PinnableItemType.toString) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "Bool" "anyPinnableItems" optionalArgs____ Decode.bool


type alias AvatarUrlOptionalArguments =
    { size : OptionalArgument Int }


{-| A URL pointing to the user's public avatar.

  - size - The size of the resulting square image.

-}
avatarUrl :
    (AvatarUrlOptionalArguments -> AvatarUrlOptionalArguments)
    -> SelectionSet Github.ScalarCodecs.Uri Github.Object.User
avatarUrl fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { size = Absent }

        optionalArgs____ =
            [ Argument.optional "size" filledInOptionals____.size Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "ScalarCodecs.Uri" "avatarUrl" optionalArgs____ (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The user's public profile bio.
-}
bio : SelectionSet (Maybe String) Github.Object.User
bio =
    Object.selectionForField "(Maybe String)" "bio" [] (Decode.string |> Decode.nullable)


{-| The user's public profile bio as HTML.
-}
bioHTML : SelectionSet Github.ScalarCodecs.Html Github.Object.User
bioHTML =
    Object.selectionForField "ScalarCodecs.Html" "bioHTML" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecHtml |> .decoder)


type alias CanReceiveOrganizationEmailsWhenNotificationsRestrictedRequiredArguments =
    { login : String }


{-| Could this user receive email notifications, if the organization had notification restrictions enabled?

  - login - The login of the organization to check.

-}
canReceiveOrganizationEmailsWhenNotificationsRestricted :
    CanReceiveOrganizationEmailsWhenNotificationsRestrictedRequiredArguments
    -> SelectionSet Bool Github.Object.User
canReceiveOrganizationEmailsWhenNotificationsRestricted requiredArgs____ =
    Object.selectionForField "Bool" "canReceiveOrganizationEmailsWhenNotificationsRestricted" [ Argument.required "login" requiredArgs____.login Encode.string ] Decode.bool


type alias CommitCommentsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of commit comments made by this user.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
commitComments :
    (CommitCommentsOptionalArguments -> CommitCommentsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.CommitCommentConnection
    -> SelectionSet decodesTo Github.Object.User
commitComments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "commitComments" optionalArgs____ object____ Basics.identity


{-| The user's public profile company.
-}
company : SelectionSet (Maybe String) Github.Object.User
company =
    Object.selectionForField "(Maybe String)" "company" [] (Decode.string |> Decode.nullable)


{-| The user's public profile company as HTML.
-}
companyHTML : SelectionSet Github.ScalarCodecs.Html Github.Object.User
companyHTML =
    Object.selectionForField "ScalarCodecs.Html" "companyHTML" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecHtml |> .decoder)


type alias ContributionsCollectionOptionalArguments =
    { organizationID : OptionalArgument Github.ScalarCodecs.Id
    , from : OptionalArgument Github.ScalarCodecs.DateTime
    , to : OptionalArgument Github.ScalarCodecs.DateTime
    }


{-| The collection of contributions this user has made to different repositories.

  - organizationID - The ID of the organization used to filter contributions.
  - from - Only contributions made at this time or later will be counted. If omitted, defaults to a year ago.
  - to - Only contributions made before and up to (including) this time will be counted. If omitted, defaults to the current time or one year from the provided from argument.

-}
contributionsCollection :
    (ContributionsCollectionOptionalArguments -> ContributionsCollectionOptionalArguments)
    -> SelectionSet decodesTo Github.Object.ContributionsCollection
    -> SelectionSet decodesTo Github.Object.User
contributionsCollection fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { organizationID = Absent, from = Absent, to = Absent }

        optionalArgs____ =
            [ Argument.optional "organizationID" filledInOptionals____.organizationID (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecId), Argument.optional "from" filledInOptionals____.from (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecDateTime), Argument.optional "to" filledInOptionals____.to (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecDateTime) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "contributionsCollection" optionalArgs____ object____ Basics.identity


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Github.ScalarCodecs.DateTime Github.Object.User
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Github.Object.User
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| The user's publicly visible profile email.
-}
email : SelectionSet String Github.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


{-| The estimated next GitHub Sponsors payout for this user/organization in cents (USD).
-}
estimatedNextSponsorsPayoutInCents : SelectionSet Int Github.Object.User
estimatedNextSponsorsPayoutInCents =
    Object.selectionForField "Int" "estimatedNextSponsorsPayoutInCents" [] Decode.int


type alias FollowersOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of users the given user is followed by.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
followers :
    (FollowersOptionalArguments -> FollowersOptionalArguments)
    -> SelectionSet decodesTo Github.Object.FollowerConnection
    -> SelectionSet decodesTo Github.Object.User
followers fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "followers" optionalArgs____ object____ Basics.identity


type alias FollowingOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of users the given user is following.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
following :
    (FollowingOptionalArguments -> FollowingOptionalArguments)
    -> SelectionSet decodesTo Github.Object.FollowingConnection
    -> SelectionSet decodesTo Github.Object.User
following fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "following" optionalArgs____ object____ Basics.identity


type alias GistRequiredArguments =
    { name : String }


{-| Find gist by repo name.

  - name - The gist name to find.

-}
gist :
    GistRequiredArguments
    -> SelectionSet decodesTo Github.Object.Gist
    -> SelectionSet (Maybe decodesTo) Github.Object.User
gist requiredArgs____ object____ =
    Object.selectionForCompositeField "gist" [ Argument.required "name" requiredArgs____.name Encode.string ] object____ (Basics.identity >> Decode.nullable)


type alias GistCommentsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of gist comments made by this user.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
gistComments :
    (GistCommentsOptionalArguments -> GistCommentsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.GistCommentConnection
    -> SelectionSet decodesTo Github.Object.User
gistComments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "gistComments" optionalArgs____ object____ Basics.identity


type alias GistsOptionalArguments =
    { privacy : OptionalArgument Github.Enum.GistPrivacy.GistPrivacy
    , orderBy : OptionalArgument Github.InputObject.GistOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of the Gists the user has created.

  - privacy - Filters Gists according to privacy.
  - orderBy - Ordering options for gists returned from the connection
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
gists :
    (GistsOptionalArguments -> GistsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.GistConnection
    -> SelectionSet decodesTo Github.Object.User
gists fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { privacy = Absent, orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "privacy" filledInOptionals____.privacy (Encode.enum Github.Enum.GistPrivacy.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeGistOrder, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "gists" optionalArgs____ object____ Basics.identity


{-| True if this user/organization has a GitHub Sponsors listing.
-}
hasSponsorsListing : SelectionSet Bool Github.Object.User
hasSponsorsListing =
    Object.selectionForField "Bool" "hasSponsorsListing" [] Decode.bool


type alias HovercardOptionalArguments =
    { primarySubjectId : OptionalArgument Github.ScalarCodecs.Id }


{-| The hovercard information for this user in a given context

  - primarySubjectId - The ID of the subject to get the hovercard in the context of

-}
hovercard :
    (HovercardOptionalArguments -> HovercardOptionalArguments)
    -> SelectionSet decodesTo Github.Object.Hovercard
    -> SelectionSet decodesTo Github.Object.User
hovercard fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { primarySubjectId = Absent }

        optionalArgs____ =
            [ Argument.optional "primarySubjectId" filledInOptionals____.primarySubjectId (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecId) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "hovercard" optionalArgs____ object____ Basics.identity


id : SelectionSet Github.ScalarCodecs.Id Github.Object.User
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The interaction ability settings for this user.
-}
interactionAbility :
    SelectionSet decodesTo Github.Object.RepositoryInteractionAbility
    -> SelectionSet (Maybe decodesTo) Github.Object.User
interactionAbility object____ =
    Object.selectionForCompositeField "interactionAbility" [] object____ (Basics.identity >> Decode.nullable)


{-| Whether or not this user is a participant in the GitHub Security Bug Bounty.
-}
isBountyHunter : SelectionSet Bool Github.Object.User
isBountyHunter =
    Object.selectionForField "Bool" "isBountyHunter" [] Decode.bool


{-| Whether or not this user is a participant in the GitHub Campus Experts Program.
-}
isCampusExpert : SelectionSet Bool Github.Object.User
isCampusExpert =
    Object.selectionForField "Bool" "isCampusExpert" [] Decode.bool


{-| Whether or not this user is a GitHub Developer Program member.
-}
isDeveloperProgramMember : SelectionSet Bool Github.Object.User
isDeveloperProgramMember =
    Object.selectionForField "Bool" "isDeveloperProgramMember" [] Decode.bool


{-| Whether or not this user is a GitHub employee.
-}
isEmployee : SelectionSet Bool Github.Object.User
isEmployee =
    Object.selectionForField "Bool" "isEmployee" [] Decode.bool


{-| Whether or not this user is following the viewer. Inverse of viewer\_is\_following
-}
isFollowingViewer : SelectionSet Bool Github.Object.User
isFollowingViewer =
    Object.selectionForField "Bool" "isFollowingViewer" [] Decode.bool


{-| Whether or not this user is a member of the GitHub Stars Program.
-}
isGitHubStar : SelectionSet Bool Github.Object.User
isGitHubStar =
    Object.selectionForField "Bool" "isGitHubStar" [] Decode.bool


{-| Whether or not the user has marked themselves as for hire.
-}
isHireable : SelectionSet Bool Github.Object.User
isHireable =
    Object.selectionForField "Bool" "isHireable" [] Decode.bool


{-| Whether or not this user is a site administrator.
-}
isSiteAdmin : SelectionSet Bool Github.Object.User
isSiteAdmin =
    Object.selectionForField "Bool" "isSiteAdmin" [] Decode.bool


type alias IsSponsoredByRequiredArguments =
    { accountLogin : String }


{-| Check if the given account is sponsoring this user/organization.

  - accountLogin - The target account's login.

-}
isSponsoredBy :
    IsSponsoredByRequiredArguments
    -> SelectionSet Bool Github.Object.User
isSponsoredBy requiredArgs____ =
    Object.selectionForField "Bool" "isSponsoredBy" [ Argument.required "accountLogin" requiredArgs____.accountLogin Encode.string ] Decode.bool


{-| True if the viewer is sponsored by this user/organization.
-}
isSponsoringViewer : SelectionSet Bool Github.Object.User
isSponsoringViewer =
    Object.selectionForField "Bool" "isSponsoringViewer" [] Decode.bool


{-| Whether or not this user is the viewing user.
-}
isViewer : SelectionSet Bool Github.Object.User
isViewer =
    Object.selectionForField "Bool" "isViewer" [] Decode.bool


type alias IssueCommentsOptionalArguments =
    { orderBy : OptionalArgument Github.InputObject.IssueCommentOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of issue comments made by this user.

  - orderBy - Ordering options for issue comments returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
issueComments :
    (IssueCommentsOptionalArguments -> IssueCommentsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.IssueCommentConnection
    -> SelectionSet decodesTo Github.Object.User
issueComments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeIssueCommentOrder, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "issueComments" optionalArgs____ object____ Basics.identity


type alias IssuesOptionalArguments =
    { orderBy : OptionalArgument Github.InputObject.IssueOrder
    , labels : OptionalArgument (List String)
    , states : OptionalArgument (List Github.Enum.IssueState.IssueState)
    , filterBy : OptionalArgument Github.InputObject.IssueFilters
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of issues associated with this user.

  - orderBy - Ordering options for issues returned from the connection.
  - labels - A list of label names to filter the pull requests by.
  - states - A list of states to filter the issues by.
  - filterBy - Filtering options for issues returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
issues :
    (IssuesOptionalArguments -> IssuesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.IssueConnection
    -> SelectionSet decodesTo Github.Object.User
issues fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { orderBy = Absent, labels = Absent, states = Absent, filterBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeIssueOrder, Argument.optional "labels" filledInOptionals____.labels (Encode.string |> Encode.list), Argument.optional "states" filledInOptionals____.states (Encode.enum Github.Enum.IssueState.toString |> Encode.list), Argument.optional "filterBy" filledInOptionals____.filterBy Github.InputObject.encodeIssueFilters, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "issues" optionalArgs____ object____ Basics.identity


{-| Showcases a selection of repositories and gists that the profile owner has either curated or that have been selected automatically based on popularity.
-}
itemShowcase :
    SelectionSet decodesTo Github.Object.ProfileItemShowcase
    -> SelectionSet decodesTo Github.Object.User
itemShowcase object____ =
    Object.selectionForCompositeField "itemShowcase" [] object____ Basics.identity


{-| The user's public profile location.
-}
location : SelectionSet (Maybe String) Github.Object.User
location =
    Object.selectionForField "(Maybe String)" "location" [] (Decode.string |> Decode.nullable)


{-| The username used to login.
-}
login : SelectionSet String Github.Object.User
login =
    Object.selectionForField "String" "login" [] Decode.string


{-| The estimated monthly GitHub Sponsors income for this user/organization in cents (USD).
-}
monthlyEstimatedSponsorsIncomeInCents : SelectionSet Int Github.Object.User
monthlyEstimatedSponsorsIncomeInCents =
    Object.selectionForField "Int" "monthlyEstimatedSponsorsIncomeInCents" [] Decode.int


{-| The user's public profile name.
-}
name : SelectionSet (Maybe String) Github.Object.User
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


type alias OrganizationRequiredArguments =
    { login : String }


{-| Find an organization by its login that the user belongs to.

  - login - The login of the organization to find.

-}
organization :
    OrganizationRequiredArguments
    -> SelectionSet decodesTo Github.Object.Organization
    -> SelectionSet (Maybe decodesTo) Github.Object.User
organization requiredArgs____ object____ =
    Object.selectionForCompositeField "organization" [ Argument.required "login" requiredArgs____.login Encode.string ] object____ (Basics.identity >> Decode.nullable)


type alias OrganizationVerifiedDomainEmailsRequiredArguments =
    { login : String }


{-| Verified email addresses that match verified domains for a specified organization the user is a member of.

  - login - The login of the organization to match verified domains from.

-}
organizationVerifiedDomainEmails :
    OrganizationVerifiedDomainEmailsRequiredArguments
    -> SelectionSet (List String) Github.Object.User
organizationVerifiedDomainEmails requiredArgs____ =
    Object.selectionForField "(List String)" "organizationVerifiedDomainEmails" [ Argument.required "login" requiredArgs____.login Encode.string ] (Decode.string |> Decode.list)


type alias OrganizationsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of organizations the user belongs to.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
organizations :
    (OrganizationsOptionalArguments -> OrganizationsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.OrganizationConnection
    -> SelectionSet decodesTo Github.Object.User
organizations fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "organizations" optionalArgs____ object____ Basics.identity


type alias PackagesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , names : OptionalArgument (List (Maybe String))
    , repositoryId : OptionalArgument Github.ScalarCodecs.Id
    , packageType : OptionalArgument Github.Enum.PackageType.PackageType
    , orderBy : OptionalArgument Github.InputObject.PackageOrder
    }


{-| A list of packages under the owner.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - names - Find packages by their names.
  - repositoryId - Find packages in a repository by ID.
  - packageType - Filter registry package by type.
  - orderBy - Ordering of the returned packages.

-}
packages :
    (PackagesOptionalArguments -> PackagesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.PackageConnection
    -> SelectionSet decodesTo Github.Object.User
packages fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, names = Absent, repositoryId = Absent, packageType = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "names" filledInOptionals____.names (Encode.string |> Encode.maybe |> Encode.list), Argument.optional "repositoryId" filledInOptionals____.repositoryId (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecId), Argument.optional "packageType" filledInOptionals____.packageType (Encode.enum Github.Enum.PackageType.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodePackageOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "packages" optionalArgs____ object____ Basics.identity


type alias PinnableItemsOptionalArguments =
    { types : OptionalArgument (List Github.Enum.PinnableItemType.PinnableItemType)
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of repositories and gists this profile owner can pin to their profile.

  - types - Filter the types of pinnable items that are returned.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
pinnableItems :
    (PinnableItemsOptionalArguments -> PinnableItemsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.PinnableItemConnection
    -> SelectionSet decodesTo Github.Object.User
pinnableItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { types = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "types" filledInOptionals____.types (Encode.enum Github.Enum.PinnableItemType.toString |> Encode.list), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "pinnableItems" optionalArgs____ object____ Basics.identity


type alias PinnedItemsOptionalArguments =
    { types : OptionalArgument (List Github.Enum.PinnableItemType.PinnableItemType)
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of repositories and gists this profile owner has pinned to their profile

  - types - Filter the types of pinned items that are returned.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
pinnedItems :
    (PinnedItemsOptionalArguments -> PinnedItemsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.PinnableItemConnection
    -> SelectionSet decodesTo Github.Object.User
pinnedItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { types = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "types" filledInOptionals____.types (Encode.enum Github.Enum.PinnableItemType.toString |> Encode.list), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "pinnedItems" optionalArgs____ object____ Basics.identity


{-| Returns how many more items this profile owner can pin to their profile.
-}
pinnedItemsRemaining : SelectionSet Int Github.Object.User
pinnedItemsRemaining =
    Object.selectionForField "Int" "pinnedItemsRemaining" [] Decode.int


type alias ProjectRequiredArguments =
    { number : Int }


{-| Find project by number.

  - number - The project number to find.

-}
project :
    ProjectRequiredArguments
    -> SelectionSet decodesTo Github.Object.Project
    -> SelectionSet (Maybe decodesTo) Github.Object.User
project requiredArgs____ object____ =
    Object.selectionForCompositeField "project" [ Argument.required "number" requiredArgs____.number Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias ProjectNextRequiredArguments =
    { number : Int }


{-| Find a project by project (beta) number.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.

  - number - The project (beta) number.

-}
projectNext :
    ProjectNextRequiredArguments
    -> SelectionSet decodesTo Github.Object.ProjectNext
    -> SelectionSet (Maybe decodesTo) Github.Object.User
projectNext requiredArgs____ object____ =
    Object.selectionForCompositeField "projectNext" [ Argument.required "number" requiredArgs____.number Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias ProjectV2RequiredArguments =
    { number : Int }


{-| Find a project by number.

  - number - The project number.

-}
projectV2 :
    ProjectV2RequiredArguments
    -> SelectionSet decodesTo Github.Object.ProjectV2
    -> SelectionSet (Maybe decodesTo) Github.Object.User
projectV2 requiredArgs____ object____ =
    Object.selectionForCompositeField "projectV2" [ Argument.required "number" requiredArgs____.number Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias ProjectsOptionalArguments =
    { orderBy : OptionalArgument Github.InputObject.ProjectOrder
    , search : OptionalArgument String
    , states : OptionalArgument (List Github.Enum.ProjectState.ProjectState)
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of projects under the owner.

  - orderBy - Ordering options for projects returned from the connection
  - search - Query to search projects by, currently only searching by name.
  - states - A list of states to filter the projects by.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projects :
    (ProjectsOptionalArguments -> ProjectsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.ProjectConnection
    -> SelectionSet decodesTo Github.Object.User
projects fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { orderBy = Absent, search = Absent, states = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeProjectOrder, Argument.optional "search" filledInOptionals____.search Encode.string, Argument.optional "states" filledInOptionals____.states (Encode.enum Github.Enum.ProjectState.toString |> Encode.list), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projects" optionalArgs____ object____ Basics.identity


type alias ProjectsNextOptionalArguments =
    { query : OptionalArgument String
    , sortBy : OptionalArgument Github.Enum.ProjectNextOrderField.ProjectNextOrderField
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of projects (beta) under the owner.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.

  - query - A project (beta) to search for under the the owner.
  - sortBy - How to order the returned projects (beta).
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projectsNext :
    (ProjectsNextOptionalArguments -> ProjectsNextOptionalArguments)
    -> SelectionSet decodesTo Github.Object.ProjectNextConnection
    -> SelectionSet decodesTo Github.Object.User
projectsNext fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { query = Absent, sortBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "query" filledInOptionals____.query Encode.string, Argument.optional "sortBy" filledInOptionals____.sortBy (Encode.enum Github.Enum.ProjectNextOrderField.toString), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectsNext" optionalArgs____ object____ Basics.identity


{-| The HTTP path listing user's projects
-}
projectsResourcePath : SelectionSet Github.ScalarCodecs.Uri Github.Object.User
projectsResourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "projectsResourcePath" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The HTTP URL listing user's projects
-}
projectsUrl : SelectionSet Github.ScalarCodecs.Uri Github.Object.User
projectsUrl =
    Object.selectionForField "ScalarCodecs.Uri" "projectsUrl" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder)


type alias ProjectsV2OptionalArguments =
    { query : OptionalArgument String
    , orderBy : OptionalArgument Github.InputObject.ProjectV2Order
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of projects under the owner.

  - query - A project to search for under the the owner.
  - orderBy - How to order the returned projects.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projectsV2 :
    (ProjectsV2OptionalArguments -> ProjectsV2OptionalArguments)
    -> SelectionSet decodesTo Github.Object.ProjectV2Connection
    -> SelectionSet decodesTo Github.Object.User
projectsV2 fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { query = Absent, orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "query" filledInOptionals____.query Encode.string, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeProjectV2Order, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectsV2" optionalArgs____ object____ Basics.identity


type alias PublicKeysOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of public keys associated with this user.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
publicKeys :
    (PublicKeysOptionalArguments -> PublicKeysOptionalArguments)
    -> SelectionSet decodesTo Github.Object.PublicKeyConnection
    -> SelectionSet decodesTo Github.Object.User
publicKeys fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "publicKeys" optionalArgs____ object____ Basics.identity


type alias PullRequestsOptionalArguments =
    { states : OptionalArgument (List Github.Enum.PullRequestState.PullRequestState)
    , labels : OptionalArgument (List String)
    , headRefName : OptionalArgument String
    , baseRefName : OptionalArgument String
    , orderBy : OptionalArgument Github.InputObject.IssueOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of pull requests associated with this user.

  - states - A list of states to filter the pull requests by.
  - labels - A list of label names to filter the pull requests by.
  - headRefName - The head ref name to filter the pull requests by.
  - baseRefName - The base ref name to filter the pull requests by.
  - orderBy - Ordering options for pull requests returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
pullRequests :
    (PullRequestsOptionalArguments -> PullRequestsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.PullRequestConnection
    -> SelectionSet decodesTo Github.Object.User
pullRequests fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { states = Absent, labels = Absent, headRefName = Absent, baseRefName = Absent, orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "states" filledInOptionals____.states (Encode.enum Github.Enum.PullRequestState.toString |> Encode.list), Argument.optional "labels" filledInOptionals____.labels (Encode.string |> Encode.list), Argument.optional "headRefName" filledInOptionals____.headRefName Encode.string, Argument.optional "baseRefName" filledInOptionals____.baseRefName Encode.string, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeIssueOrder, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "pullRequests" optionalArgs____ object____ Basics.identity


type alias RecentProjectsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| Recent projects that this user has modified in the context of the owner.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
recentProjects :
    (RecentProjectsOptionalArguments -> RecentProjectsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.ProjectV2Connection
    -> SelectionSet decodesTo Github.Object.User
recentProjects fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "recentProjects" optionalArgs____ object____ Basics.identity


type alias RepositoriesOptionalArguments =
    { privacy : OptionalArgument Github.Enum.RepositoryPrivacy.RepositoryPrivacy
    , orderBy : OptionalArgument Github.InputObject.RepositoryOrder
    , affiliations : OptionalArgument (List (Maybe Github.Enum.RepositoryAffiliation.RepositoryAffiliation))
    , ownerAffiliations : OptionalArgument (List (Maybe Github.Enum.RepositoryAffiliation.RepositoryAffiliation))
    , isLocked : OptionalArgument Bool
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , isFork : OptionalArgument Bool
    }


{-| A list of repositories that the user owns.

  - privacy - If non-null, filters repositories according to privacy
  - orderBy - Ordering options for repositories returned from the connection
  - affiliations - Array of viewer's affiliation options for repositories returned from the connection. For example, OWNER will include only repositories that the current viewer owns.
  - ownerAffiliations - Array of owner's affiliation options for repositories returned from the connection. For example, OWNER will include only repositories that the organization or user being viewed owns.
  - isLocked - If non-null, filters repositories according to whether they have been locked
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - isFork - If non-null, filters repositories according to whether they are forks of another repository

-}
repositories :
    (RepositoriesOptionalArguments -> RepositoriesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.RepositoryConnection
    -> SelectionSet decodesTo Github.Object.User
repositories fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { privacy = Absent, orderBy = Absent, affiliations = Absent, ownerAffiliations = Absent, isLocked = Absent, after = Absent, before = Absent, first = Absent, last = Absent, isFork = Absent }

        optionalArgs____ =
            [ Argument.optional "privacy" filledInOptionals____.privacy (Encode.enum Github.Enum.RepositoryPrivacy.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeRepositoryOrder, Argument.optional "affiliations" filledInOptionals____.affiliations (Encode.enum Github.Enum.RepositoryAffiliation.toString |> Encode.maybe |> Encode.list), Argument.optional "ownerAffiliations" filledInOptionals____.ownerAffiliations (Encode.enum Github.Enum.RepositoryAffiliation.toString |> Encode.maybe |> Encode.list), Argument.optional "isLocked" filledInOptionals____.isLocked Encode.bool, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "isFork" filledInOptionals____.isFork Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "repositories" optionalArgs____ object____ Basics.identity


type alias RepositoriesContributedToOptionalArguments =
    { privacy : OptionalArgument Github.Enum.RepositoryPrivacy.RepositoryPrivacy
    , orderBy : OptionalArgument Github.InputObject.RepositoryOrder
    , isLocked : OptionalArgument Bool
    , includeUserRepositories : OptionalArgument Bool
    , contributionTypes : OptionalArgument (List (Maybe Github.Enum.RepositoryContributionType.RepositoryContributionType))
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of repositories that the user recently contributed to.

  - privacy - If non-null, filters repositories according to privacy
  - orderBy - Ordering options for repositories returned from the connection
  - isLocked - If non-null, filters repositories according to whether they have been locked
  - includeUserRepositories - If true, include user repositories
  - contributionTypes - If non-null, include only the specified types of contributions. The GitHub.com UI uses [COMMIT, ISSUE, PULL\_REQUEST, REPOSITORY][COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
repositoriesContributedTo :
    (RepositoriesContributedToOptionalArguments -> RepositoriesContributedToOptionalArguments)
    -> SelectionSet decodesTo Github.Object.RepositoryConnection
    -> SelectionSet decodesTo Github.Object.User
repositoriesContributedTo fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { privacy = Absent, orderBy = Absent, isLocked = Absent, includeUserRepositories = Absent, contributionTypes = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "privacy" filledInOptionals____.privacy (Encode.enum Github.Enum.RepositoryPrivacy.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeRepositoryOrder, Argument.optional "isLocked" filledInOptionals____.isLocked Encode.bool, Argument.optional "includeUserRepositories" filledInOptionals____.includeUserRepositories Encode.bool, Argument.optional "contributionTypes" filledInOptionals____.contributionTypes (Encode.enum Github.Enum.RepositoryContributionType.toString |> Encode.maybe |> Encode.list), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "repositoriesContributedTo" optionalArgs____ object____ Basics.identity


type alias RepositoryOptionalArguments =
    { followRenames : OptionalArgument Bool }


type alias RepositoryRequiredArguments =
    { name : String }


{-| Find Repository.

  - name - Name of Repository to find.
  - followRenames - Follow repository renames. If disabled, a repository referenced by its old name will return an error.

-}
repository :
    (RepositoryOptionalArguments -> RepositoryOptionalArguments)
    -> RepositoryRequiredArguments
    -> SelectionSet decodesTo Github.Object.Repository
    -> SelectionSet (Maybe decodesTo) Github.Object.User
repository fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { followRenames = Absent }

        optionalArgs____ =
            [ Argument.optional "followRenames" filledInOptionals____.followRenames Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "repository" (optionalArgs____ ++ [ Argument.required "name" requiredArgs____.name Encode.string ]) object____ (Basics.identity >> Decode.nullable)


type alias RepositoryDiscussionCommentsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , repositoryId : OptionalArgument Github.ScalarCodecs.Id
    , onlyAnswers : OptionalArgument Bool
    }


{-| Discussion comments this user has authored.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - repositoryId - Filter discussion comments to only those in a specific repository.
  - onlyAnswers - Filter discussion comments to only those that were marked as the answer

-}
repositoryDiscussionComments :
    (RepositoryDiscussionCommentsOptionalArguments -> RepositoryDiscussionCommentsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.DiscussionCommentConnection
    -> SelectionSet decodesTo Github.Object.User
repositoryDiscussionComments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, repositoryId = Absent, onlyAnswers = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "repositoryId" filledInOptionals____.repositoryId (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecId), Argument.optional "onlyAnswers" filledInOptionals____.onlyAnswers Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "repositoryDiscussionComments" optionalArgs____ object____ Basics.identity


type alias RepositoryDiscussionsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , orderBy : OptionalArgument Github.InputObject.DiscussionOrder
    , repositoryId : OptionalArgument Github.ScalarCodecs.Id
    , answered : OptionalArgument Bool
    }


{-| Discussions this user has started.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - Ordering options for discussions returned from the connection.
  - repositoryId - Filter discussions to only those in a specific repository.
  - answered - Filter discussions to only those that have been answered or not. Defaults to including both answered and unanswered discussions.

-}
repositoryDiscussions :
    (RepositoryDiscussionsOptionalArguments -> RepositoryDiscussionsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.DiscussionConnection
    -> SelectionSet decodesTo Github.Object.User
repositoryDiscussions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, orderBy = Absent, repositoryId = Absent, answered = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeDiscussionOrder, Argument.optional "repositoryId" filledInOptionals____.repositoryId (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecId), Argument.optional "answered" filledInOptionals____.answered Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "repositoryDiscussions" optionalArgs____ object____ Basics.identity


{-| The HTTP path for this user
-}
resourcePath : SelectionSet Github.ScalarCodecs.Uri Github.Object.User
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder)


type alias SavedRepliesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , orderBy : OptionalArgument Github.InputObject.SavedReplyOrder
    }


{-| Replies this user has saved

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - The field to order saved replies by.

-}
savedReplies :
    (SavedRepliesOptionalArguments -> SavedRepliesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SavedReplyConnection
    -> SelectionSet (Maybe decodesTo) Github.Object.User
savedReplies fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSavedReplyOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "savedReplies" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias SponsoringOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , orderBy : OptionalArgument Github.InputObject.SponsorOrder
    }


{-| List of users and organizations this entity is sponsoring.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - Ordering options for the users and organizations returned from the connection.

-}
sponsoring :
    (SponsoringOptionalArguments -> SponsoringOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SponsorConnection
    -> SelectionSet decodesTo Github.Object.User
sponsoring fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSponsorOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "sponsoring" optionalArgs____ object____ Basics.identity


type alias SponsorsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , tierId : OptionalArgument Github.ScalarCodecs.Id
    , orderBy : OptionalArgument Github.InputObject.SponsorOrder
    }


{-| List of sponsors for this user or organization.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - tierId - If given, will filter for sponsors at the given tier. Will only return sponsors whose tier the viewer is permitted to see.
  - orderBy - Ordering options for sponsors returned from the connection.

-}
sponsors :
    (SponsorsOptionalArguments -> SponsorsOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SponsorConnection
    -> SelectionSet decodesTo Github.Object.User
sponsors fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, tierId = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "tierId" filledInOptionals____.tierId (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecId), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSponsorOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "sponsors" optionalArgs____ object____ Basics.identity


type alias SponsorsActivitiesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , period : OptionalArgument Github.Enum.SponsorsActivityPeriod.SponsorsActivityPeriod
    , orderBy : OptionalArgument Github.InputObject.SponsorsActivityOrder
    , actions : OptionalArgument (List Github.Enum.SponsorsActivityAction.SponsorsActivityAction)
    }


{-| Events involving this sponsorable, such as new sponsorships.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - period - Filter activities returned to only those that occurred in the most recent specified time period. Set to ALL to avoid filtering by when the activity occurred.
  - orderBy - Ordering options for activity returned from the connection.
  - actions - Filter activities to only the specified actions.

-}
sponsorsActivities :
    (SponsorsActivitiesOptionalArguments -> SponsorsActivitiesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SponsorsActivityConnection
    -> SelectionSet decodesTo Github.Object.User
sponsorsActivities fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, period = Absent, orderBy = Absent, actions = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "period" filledInOptionals____.period (Encode.enum Github.Enum.SponsorsActivityPeriod.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSponsorsActivityOrder, Argument.optional "actions" filledInOptionals____.actions (Encode.enum Github.Enum.SponsorsActivityAction.toString |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "sponsorsActivities" optionalArgs____ object____ Basics.identity


{-| The GitHub Sponsors listing for this user or organization.
-}
sponsorsListing :
    SelectionSet decodesTo Github.Object.SponsorsListing
    -> SelectionSet (Maybe decodesTo) Github.Object.User
sponsorsListing object____ =
    Object.selectionForCompositeField "sponsorsListing" [] object____ (Basics.identity >> Decode.nullable)


{-| The sponsorship from the viewer to this user/organization; that is, the sponsorship where you're the sponsor. Only returns a sponsorship if it is active.
-}
sponsorshipForViewerAsSponsor :
    SelectionSet decodesTo Github.Object.Sponsorship
    -> SelectionSet (Maybe decodesTo) Github.Object.User
sponsorshipForViewerAsSponsor object____ =
    Object.selectionForCompositeField "sponsorshipForViewerAsSponsor" [] object____ (Basics.identity >> Decode.nullable)


{-| The sponsorship from this user/organization to the viewer; that is, the sponsorship you're receiving. Only returns a sponsorship if it is active.
-}
sponsorshipForViewerAsSponsorable :
    SelectionSet decodesTo Github.Object.Sponsorship
    -> SelectionSet (Maybe decodesTo) Github.Object.User
sponsorshipForViewerAsSponsorable object____ =
    Object.selectionForCompositeField "sponsorshipForViewerAsSponsorable" [] object____ (Basics.identity >> Decode.nullable)


type alias SponsorshipNewslettersOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , orderBy : OptionalArgument Github.InputObject.SponsorshipNewsletterOrder
    }


{-| List of sponsorship updates sent from this sponsorable to sponsors.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - Ordering options for sponsorship updates returned from the connection.

-}
sponsorshipNewsletters :
    (SponsorshipNewslettersOptionalArguments -> SponsorshipNewslettersOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SponsorshipNewsletterConnection
    -> SelectionSet decodesTo Github.Object.User
sponsorshipNewsletters fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSponsorshipNewsletterOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "sponsorshipNewsletters" optionalArgs____ object____ Basics.identity


type alias SponsorshipsAsMaintainerOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , includePrivate : OptionalArgument Bool
    , orderBy : OptionalArgument Github.InputObject.SponsorshipOrder
    }


{-| This object's sponsorships as the maintainer.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - includePrivate - Whether or not to include private sponsorships in the result set
  - orderBy - Ordering options for sponsorships returned from this connection. If left blank, the sponsorships will be ordered based on relevancy to the viewer.

-}
sponsorshipsAsMaintainer :
    (SponsorshipsAsMaintainerOptionalArguments -> SponsorshipsAsMaintainerOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SponsorshipConnection
    -> SelectionSet decodesTo Github.Object.User
sponsorshipsAsMaintainer fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, includePrivate = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "includePrivate" filledInOptionals____.includePrivate Encode.bool, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSponsorshipOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "sponsorshipsAsMaintainer" optionalArgs____ object____ Basics.identity


type alias SponsorshipsAsSponsorOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , orderBy : OptionalArgument Github.InputObject.SponsorshipOrder
    }


{-| This object's sponsorships as the sponsor.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - Ordering options for sponsorships returned from this connection. If left blank, the sponsorships will be ordered based on relevancy to the viewer.

-}
sponsorshipsAsSponsor :
    (SponsorshipsAsSponsorOptionalArguments -> SponsorshipsAsSponsorOptionalArguments)
    -> SelectionSet decodesTo Github.Object.SponsorshipConnection
    -> SelectionSet decodesTo Github.Object.User
sponsorshipsAsSponsor fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeSponsorshipOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "sponsorshipsAsSponsor" optionalArgs____ object____ Basics.identity


type alias StarredRepositoriesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , ownedByViewer : OptionalArgument Bool
    , orderBy : OptionalArgument Github.InputObject.StarOrder
    }


{-| Repositories the user has starred.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - ownedByViewer - Filters starred repositories to only return repositories owned by the viewer.
  - orderBy - Order for connection

-}
starredRepositories :
    (StarredRepositoriesOptionalArguments -> StarredRepositoriesOptionalArguments)
    -> SelectionSet decodesTo Github.Object.StarredRepositoryConnection
    -> SelectionSet decodesTo Github.Object.User
starredRepositories fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, ownedByViewer = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "ownedByViewer" filledInOptionals____.ownedByViewer Encode.bool, Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeStarOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "starredRepositories" optionalArgs____ object____ Basics.identity


{-| The user's description of what they're currently doing.
-}
status :
    SelectionSet decodesTo Github.Object.UserStatus
    -> SelectionSet (Maybe decodesTo) Github.Object.User
status object____ =
    Object.selectionForCompositeField "status" [] object____ (Basics.identity >> Decode.nullable)


type alias TopRepositoriesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , since : OptionalArgument Github.ScalarCodecs.DateTime
    }


type alias TopRepositoriesRequiredArguments =
    { orderBy : Github.InputObject.RepositoryOrder }


{-| Repositories the user has contributed to, ordered by contribution rank, plus repositories the user has created

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - Ordering options for repositories returned from the connection
  - since - How far back in time to fetch contributed repositories

-}
topRepositories :
    (TopRepositoriesOptionalArguments -> TopRepositoriesOptionalArguments)
    -> TopRepositoriesRequiredArguments
    -> SelectionSet decodesTo Github.Object.RepositoryConnection
    -> SelectionSet decodesTo Github.Object.User
topRepositories fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, since = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "since" filledInOptionals____.since (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapEncoder .codecDateTime) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "topRepositories" (optionalArgs____ ++ [ Argument.required "orderBy" requiredArgs____.orderBy Github.InputObject.encodeRepositoryOrder ]) object____ Basics.identity


{-| The user's Twitter username.
-}
twitterUsername : SelectionSet (Maybe String) Github.Object.User
twitterUsername =
    Object.selectionForField "(Maybe String)" "twitterUsername" [] (Decode.string |> Decode.nullable)


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet Github.ScalarCodecs.DateTime Github.Object.User
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The HTTP URL for this user
-}
url : SelectionSet Github.ScalarCodecs.Uri Github.Object.User
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| Can the viewer pin repositories and gists to the profile?
-}
viewerCanChangePinnedItems : SelectionSet Bool Github.Object.User
viewerCanChangePinnedItems =
    Object.selectionForField "Bool" "viewerCanChangePinnedItems" [] Decode.bool


{-| Can the current viewer create new projects on this owner.
-}
viewerCanCreateProjects : SelectionSet Bool Github.Object.User
viewerCanCreateProjects =
    Object.selectionForField "Bool" "viewerCanCreateProjects" [] Decode.bool


{-| Whether or not the viewer is able to follow the user.
-}
viewerCanFollow : SelectionSet Bool Github.Object.User
viewerCanFollow =
    Object.selectionForField "Bool" "viewerCanFollow" [] Decode.bool


{-| Whether or not the viewer is able to sponsor this user/organization.
-}
viewerCanSponsor : SelectionSet Bool Github.Object.User
viewerCanSponsor =
    Object.selectionForField "Bool" "viewerCanSponsor" [] Decode.bool


{-| Whether or not this user is followed by the viewer. Inverse of is\_following\_viewer.
-}
viewerIsFollowing : SelectionSet Bool Github.Object.User
viewerIsFollowing =
    Object.selectionForField "Bool" "viewerIsFollowing" [] Decode.bool


{-| True if the viewer is sponsoring this user/organization.
-}
viewerIsSponsoring : SelectionSet Bool Github.Object.User
viewerIsSponsoring =
    Object.selectionForField "Bool" "viewerIsSponsoring" [] Decode.bool


type alias WatchingOptionalArguments =
    { privacy : OptionalArgument Github.Enum.RepositoryPrivacy.RepositoryPrivacy
    , orderBy : OptionalArgument Github.InputObject.RepositoryOrder
    , affiliations : OptionalArgument (List (Maybe Github.Enum.RepositoryAffiliation.RepositoryAffiliation))
    , ownerAffiliations : OptionalArgument (List (Maybe Github.Enum.RepositoryAffiliation.RepositoryAffiliation))
    , isLocked : OptionalArgument Bool
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of repositories the given user is watching.

  - privacy - If non-null, filters repositories according to privacy
  - orderBy - Ordering options for repositories returned from the connection
  - affiliations - Affiliation options for repositories returned from the connection. If none specified, the results will include repositories for which the current viewer is an owner or collaborator, or member.
  - ownerAffiliations - Array of owner's affiliation options for repositories returned from the connection. For example, OWNER will include only repositories that the organization or user being viewed owns.
  - isLocked - If non-null, filters repositories according to whether they have been locked
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
watching :
    (WatchingOptionalArguments -> WatchingOptionalArguments)
    -> SelectionSet decodesTo Github.Object.RepositoryConnection
    -> SelectionSet decodesTo Github.Object.User
watching fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { privacy = Absent, orderBy = Absent, affiliations = Absent, ownerAffiliations = Absent, isLocked = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "privacy" filledInOptionals____.privacy (Encode.enum Github.Enum.RepositoryPrivacy.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Github.InputObject.encodeRepositoryOrder, Argument.optional "affiliations" filledInOptionals____.affiliations (Encode.enum Github.Enum.RepositoryAffiliation.toString |> Encode.maybe |> Encode.list), Argument.optional "ownerAffiliations" filledInOptionals____.ownerAffiliations (Encode.enum Github.Enum.RepositoryAffiliation.toString |> Encode.maybe |> Encode.list), Argument.optional "isLocked" filledInOptionals____.isLocked Encode.bool, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "watching" optionalArgs____ object____ Basics.identity


{-| A URL pointing to the user's public website/blog.
-}
websiteUrl : SelectionSet (Maybe Github.ScalarCodecs.Uri) Github.Object.User
websiteUrl =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "websiteUrl" [] (Github.ScalarCodecs.codecs |> Github.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)
