-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Enum.OrgEnterpriseOwnerOrderField exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Properties by which enterprise owners can be ordered.

  - Login - Order enterprise owners by login.

-}
type OrgEnterpriseOwnerOrderField
    = Login


list : List OrgEnterpriseOwnerOrderField
list =
    [ Login ]


decoder : Decoder OrgEnterpriseOwnerOrderField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "LOGIN" ->
                        Decode.succeed Login

                    _ ->
                        Decode.fail ("Invalid OrgEnterpriseOwnerOrderField type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : OrgEnterpriseOwnerOrderField -> String
toString enum____ =
    case enum____ of
        Login ->
            "LOGIN"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe OrgEnterpriseOwnerOrderField
fromString enumString____ =
    case enumString____ of
        "LOGIN" ->
            Just Login

        _ ->
            Nothing
