-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Enum.OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The permissions available for repository creation on an Organization.

  - All - All organization members are restricted from creating any repositories.
  - Public - All organization members are restricted from creating public repositories.
  - None - All organization members are allowed to create any repositories.
  - Private - All organization members are restricted from creating private repositories.
  - Internal - All organization members are restricted from creating internal repositories.
  - PublicInternal - All organization members are restricted from creating public or internal repositories.
  - PrivateInternal - All organization members are restricted from creating private or internal repositories.
  - PublicPrivate - All organization members are restricted from creating public or private repositories.

-}
type OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility
    = All
    | Public
    | None
    | Private
    | Internal
    | PublicInternal
    | PrivateInternal
    | PublicPrivate


list : List OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility
list =
    [ All, Public, None, Private, Internal, PublicInternal, PrivateInternal, PublicPrivate ]


decoder : Decoder OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ALL" ->
                        Decode.succeed All

                    "PUBLIC" ->
                        Decode.succeed Public

                    "NONE" ->
                        Decode.succeed None

                    "PRIVATE" ->
                        Decode.succeed Private

                    "INTERNAL" ->
                        Decode.succeed Internal

                    "PUBLIC_INTERNAL" ->
                        Decode.succeed PublicInternal

                    "PRIVATE_INTERNAL" ->
                        Decode.succeed PrivateInternal

                    "PUBLIC_PRIVATE" ->
                        Decode.succeed PublicPrivate

                    _ ->
                        Decode.fail ("Invalid OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility -> String
toString enum____ =
    case enum____ of
        All ->
            "ALL"

        Public ->
            "PUBLIC"

        None ->
            "NONE"

        Private ->
            "PRIVATE"

        Internal ->
            "INTERNAL"

        PublicInternal ->
            "PUBLIC_INTERNAL"

        PrivateInternal ->
            "PRIVATE_INTERNAL"

        PublicPrivate ->
            "PUBLIC_PRIVATE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe OrgUpdateMemberRepositoryCreationPermissionAuditEntryVisibility
fromString enumString____ =
    case enumString____ of
        "ALL" ->
            Just All

        "PUBLIC" ->
            Just Public

        "NONE" ->
            Just None

        "PRIVATE" ->
            Just Private

        "INTERNAL" ->
            Just Internal

        "PUBLIC_INTERNAL" ->
            Just PublicInternal

        "PRIVATE_INTERNAL" ->
            Just PrivateInternal

        "PUBLIC_PRIVATE" ->
            Just PublicPrivate

        _ ->
            Nothing
