-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Enum.SponsorOrderField exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Properties by which sponsor connections can be ordered.

  - Login - Order sponsorable entities by login (username).
  - Relevance - Order sponsors by their relevance to the viewer.

-}
type SponsorOrderField
    = Login
    | Relevance


list : List SponsorOrderField
list =
    [ Login, Relevance ]


decoder : Decoder SponsorOrderField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "LOGIN" ->
                        Decode.succeed Login

                    "RELEVANCE" ->
                        Decode.succeed Relevance

                    _ ->
                        Decode.fail ("Invalid SponsorOrderField type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SponsorOrderField -> String
toString enum____ =
    case enum____ of
        Login ->
            "LOGIN"

        Relevance ->
            "RELEVANCE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SponsorOrderField
fromString enumString____ =
    case enumString____ of
        "LOGIN" ->
            Just Login

        "RELEVANCE" ->
            Just Relevance

        _ ->
            Nothing
