-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Enum.SquashMergeCommitTitle exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The possible default commit titles for squash merges.

  - PrTitle - Default to the pull request's title.
  - CommitOrPrTitle - Default to the commit's title (if only one commit) or the pull request's title (when more than one commit).

-}
type SquashMergeCommitTitle
    = PrTitle
    | CommitOrPrTitle


list : List SquashMergeCommitTitle
list =
    [ PrTitle, CommitOrPrTitle ]


decoder : Decoder SquashMergeCommitTitle
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PR_TITLE" ->
                        Decode.succeed PrTitle

                    "COMMIT_OR_PR_TITLE" ->
                        Decode.succeed CommitOrPrTitle

                    _ ->
                        Decode.fail ("Invalid SquashMergeCommitTitle type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SquashMergeCommitTitle -> String
toString enum____ =
    case enum____ of
        PrTitle ->
            "PR_TITLE"

        CommitOrPrTitle ->
            "COMMIT_OR_PR_TITLE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SquashMergeCommitTitle
fromString enumString____ =
    case enumString____ of
        "PR_TITLE" ->
            Just PrTitle

        "COMMIT_OR_PR_TITLE" ->
            Just CommitOrPrTitle

        _ ->
            Nothing
